package update_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/23min/aiwf/internal/config"
	"github.com/23min/aiwf/internal/testsupport"
)

const legacyHandoverBlock = "<!-- ai-dotfiles:stack:START (generated by dotfiles-sync; do not edit) -->\n@~/.agents/guidance/200-go.md\n<!-- ai-dotfiles:stack:END -->\n"

func TestRun_ProjectGuidanceHandover(t *testing.T) {
	for _, kind := range []string{"absent installation", "compatible checker", "incompatible checker", "missing checker", "empty selection", "disabled", "unavailable source"} {
		t.Run(kind, func(t *testing.T) {
			bin := testsupport.IsolateGuidanceEnvironment(t)
			root, source := freshInitializedRepo(t), testsupport.GuidanceSource(t)
			selection := "[sample/base]"
			if kind == "empty selection" {
				selection = "[]"
			}
			guidanceConfig(t, root, source, selection, false)
			guidanceUpdate(t, root)
			guidanceConfig(t, root, source, selection, kind != "disabled")
			for _, host := range []string{"CLAUDE.md", "AGENTS.md"} {
				original, err := os.ReadFile(filepath.Join(root, host))
				if err != nil {
					t.Fatal(err)
				}
				guidanceWrite(t, root, host, string(original)+"\n# Personal rules\n"+legacyHandoverBlock)
			}
			before := guidanceFiles(t, root)
			checker := filepath.Join(bin, "dotfiles-guidance-check")
			switch kind {
			case "compatible checker", "empty selection", "unavailable source":
				if err := testsupport.WriteExecutable(checker, []byte("#!/bin/sh\nexit 0\n")); err != nil {
					t.Fatal(err)
				}
			case "incompatible checker", "disabled":
				if err := testsupport.WriteExecutable(checker, []byte("#!/bin/sh\nprintf 'reconcile old Claude routing\\n' >&2\nexit 1\n")); err != nil {
					t.Fatal(err)
				}
			case "missing checker":
				guidanceWrite(t, os.Getenv("HOME"), ".claude/CLAUDE.md", "# ai-dotfiles legacy guidance\n")
			}
			if kind == "unavailable source" {
				guidanceConfig(t, root, filepath.Join(root, "missing"), selection, true)
			}
			example := filepath.Join(root, config.ExampleFileName)
			if err := os.Remove(example); err != nil {
				t.Fatal(err)
			}
			output := guidanceUpdate(t, root)
			after := guidanceFiles(t, root)
			blocked := kind == "incompatible checker" || kind == "missing checker" || kind == "unavailable source"
			if blocked || kind == "disabled" {
				if diff := cmp.Diff(before, after); diff != "" {
					t.Fatalf("blocked handover changed guidance: %s", diff)
				}
				if blocked && !strings.Contains(output, "guidance incomplete") {
					t.Fatalf("missing handover refusal: %s", output)
				}
			} else {
				if !strings.Contains(after[".guidance/index.md"], "<!-- aiwf:engineering-guidance -->") {
					t.Fatalf("handover did not establish ownership: %s", output)
				}
				for _, host := range []string{"CLAUDE.md", "AGENTS.md"} {
					if strings.Contains(after[host], "@~/.agents/guidance/") || !strings.Contains(after[host], ".guidance/index.md") || !strings.Contains(after[host], "# Personal rules") {
						t.Fatalf("duplicate guidance or lost personal rules: %s", after[host])
					}
				}
				guidanceUpdate(t, root)
				if diff := cmp.Diff(after, guidanceFiles(t, root)); diff != "" {
					t.Fatalf("repeated handover changed guidance: %s", diff)
				}
			}
			if _, err := os.Stat(example); err != nil {
				t.Fatalf("unrelated update did not continue: %v", err)
			}
		})
	}
}
