package update_test

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/23min/aiwf/internal/cli/cliutil"
	"github.com/23min/aiwf/internal/cli/update"
	"github.com/23min/aiwf/internal/config"
)

func TestRun_ProjectGuidancePreservesConfigurationAndLegacyOwnership(t *testing.T) {
	t.Parallel()
	for _, selection := range []string{"", "  enabled: false\n  packs: [go/cobra]\n  ignored: [python/astral]\n"} {
		t.Run(selection, func(t *testing.T) {
			t.Parallel()
			root := freshInitializedRepo(t)
			original := []byte("# Preserve operator notes.\nhosts: []\ncustom_setting: retained\nguidance:\n  wire_claudemd: false\n  wire_agentsmd: false\n" + selection)
			path := filepath.Join(root, config.FileName)
			if err := os.WriteFile(path, original, 0o644); err != nil {
				t.Fatal(err)
			}
			legacy := []byte("# Project\n<!-- ai-dotfiles:stack:START (generated by dotfiles-sync; do not edit) -->\n@~/.agents/guidance/200-go.md\n<!-- ai-dotfiles:stack:END -->\n")
			if err := os.WriteFile(filepath.Join(root, "CLAUDE.md"), legacy, 0o644); err != nil {
				t.Fatal(err)
			}
			if rc := update.Run(root, false, "", false, false, false, false, nil, nil); rc != cliutil.ExitOK {
				t.Fatalf("update exit %d", rc)
			}
			for name, want := range map[string][]byte{config.FileName: original, "CLAUDE.md": legacy} {
				got, err := os.ReadFile(filepath.Join(root, name))
				if err != nil || !bytes.Equal(got, want) {
					t.Fatalf("%s changed: %s (%v)", name, got, err)
				}
			}
			if _, err := os.Stat(filepath.Join(root, ".guidance", "index.md")); !errors.Is(err, fs.ErrNotExist) {
				t.Fatalf("unadopted/disabled guidance claimed ownership: %v", err)
			}
		})
	}
}

func TestRun_ProjectGuidanceRejectsOverlapBeforeRefresh(t *testing.T) {
	t.Parallel()
	root := freshInitializedRepo(t)
	original := []byte("hosts: []\nguidance: {packs: [go/cobra], ignored: [go/cobra]}\n")
	path := filepath.Join(root, config.FileName)
	if err := os.WriteFile(path, original, 0o644); err != nil {
		t.Fatal(err)
	}
	example := filepath.Join(root, config.ExampleFileName)
	if err := os.WriteFile(example, []byte("unchanged\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if rc := update.Run(root, false, "", false, false, false, false, nil, nil); rc != cliutil.ExitInternal {
		t.Fatalf("invalid configuration exit %d", rc)
	}
	for name, want := range map[string][]byte{config.FileName: original, config.ExampleFileName: []byte("unchanged\n")} {
		got, err := os.ReadFile(filepath.Join(root, name))
		if err != nil || !bytes.Equal(got, want) {
			t.Fatalf("%s changed on rejected configuration: %s (%v)", name, got, err)
		}
	}
}
