package update_test

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/23min/aiwf/internal/cli/cliutil"
	"github.com/23min/aiwf/internal/cli/update"
	"github.com/23min/aiwf/internal/config"
	"github.com/23min/aiwf/internal/gitops"
	"github.com/23min/aiwf/internal/testsupport"
)

func TestRun_ProjectGuidancePreservesConfigurationAndLegacyOwnership(t *testing.T) {
	t.Parallel()
	for _, selection := range []string{"", "  enabled: false\n  packs: [go/cobra]\n  ignored: [python/astral]\n"} {
		t.Run(selection, func(t *testing.T) {
			t.Parallel()
			root := freshInitializedRepo(t)
			original := []byte("# Preserve operator notes.\nhosts: []\ncustom_setting: retained\nguidance:\n  wire_claudemd: false\n  wire_agentsmd: false\n" + selection)
			path := filepath.Join(root, config.FileName)
			if err := os.WriteFile(path, original, 0o644); err != nil {
				t.Fatal(err)
			}
			legacy := []byte("# Project\n<!-- ai-dotfiles:stack:START (generated by dotfiles-sync; do not edit) -->\n@~/.agents/guidance/200-go.md\n<!-- ai-dotfiles:stack:END -->\n")
			if err := os.WriteFile(filepath.Join(root, "CLAUDE.md"), legacy, 0o644); err != nil {
				t.Fatal(err)
			}
			if rc := update.Run(root, false, "", false, false, false, false, false, nil, nil); rc != cliutil.ExitOK {
				t.Fatalf("update exit %d", rc)
			}
			for name, want := range map[string][]byte{config.FileName: original, "CLAUDE.md": legacy} {
				got, err := os.ReadFile(filepath.Join(root, name))
				if err != nil || !bytes.Equal(got, want) {
					t.Fatalf("%s changed: %s (%v)", name, got, err)
				}
			}
			if _, err := os.Stat(filepath.Join(root, ".guidance", "index.md")); !errors.Is(err, fs.ErrNotExist) {
				t.Fatalf("unadopted/disabled guidance claimed ownership: %v", err)
			}
		})
	}
}

func TestRun_ProjectGuidanceRejectsOverlapBeforeRefresh(t *testing.T) {
	t.Parallel()
	root := freshInitializedRepo(t)
	original := []byte("hosts: []\nguidance: {packs: [go/cobra], ignored: [go/cobra]}\n")
	path := filepath.Join(root, config.FileName)
	if err := os.WriteFile(path, original, 0o644); err != nil {
		t.Fatal(err)
	}
	example := filepath.Join(root, config.ExampleFileName)
	if err := os.WriteFile(example, []byte("unchanged\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if rc := update.Run(root, false, "", false, false, false, false, false, nil, nil); rc != cliutil.ExitInternal {
		t.Fatalf("invalid configuration exit %d", rc)
	}
	for name, want := range map[string][]byte{config.FileName: original, config.ExampleFileName: []byte("unchanged\n")} {
		got, err := os.ReadFile(filepath.Join(root, name))
		if err != nil || !bytes.Equal(got, want) {
			t.Fatalf("%s changed on rejected configuration: %s (%v)", name, got, err)
		}
	}
}

func TestRun_ProjectGuidanceTracksUpstreamAndConverges(t *testing.T) {
	testsupport.IsolateGuidanceEnvironment(t)
	root, source := freshInitializedRepo(t), testsupport.GuidanceSource(t)
	cfg := "hosts: [claude-code, codex]\nguidance:\n  source: " + source + "\n  packs: [sample/base]\n"
	if err := os.WriteFile(filepath.Join(root, config.FileName), []byte(cfg), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := gitops.CommitAllowEmpty(t.Context(), root, "fixture baseline", "", nil); err != nil {
		t.Fatal(err)
	}
	before, headErr := gitops.ResolveCommitSHA(t.Context(), root, "HEAD")
	if headErr != nil {
		t.Fatal(headErr)
	}
	for _, content := range []string{"# First upstream revision\n", "# Second upstream revision\n"} {
		if err := os.WriteFile(filepath.Join(source, "packs", "sample", "base", "guide.md"), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		commit := testsupport.CommitGuidanceSource(t, source)
		trace := filepath.Join(t.TempDir(), "git-trace")
		t.Setenv("GIT_TRACE", trace)
		if rc := update.Run(root, false, "", false, false, false, false, false, nil, nil); rc != cliutil.ExitOK {
			t.Fatalf("update exit %d", rc)
		}
		installed, err := os.ReadFile(filepath.Join(root, ".guidance", "packs", "sample", "base", "guide.md"))
		if err != nil || string(installed) != content {
			t.Fatalf("installed = %s, %v", installed, err)
		}
		index, err := os.ReadFile(filepath.Join(root, ".guidance", "index.md"))
		if err != nil || !bytes.Contains(index, []byte(commit)) {
			t.Fatalf("index revision: %s, %v", index, err)
		}
		if rc := update.Run(root, false, "", false, false, false, false, false, nil, nil); rc != cliutil.ExitOK {
			t.Fatalf("repeat update exit %d", rc)
		}
		repeated, err := os.ReadFile(filepath.Join(root, ".guidance", "index.md"))
		if err != nil || !bytes.Equal(index, repeated) {
			t.Fatalf("unchanged upstream changed index: %s, %v", repeated, err)
		}
		after, headErr := gitops.ResolveCommitSHA(t.Context(), root, "HEAD")
		if headErr != nil || after != before {
			t.Fatalf("update changed HEAD: %s -> %s (%v)", before, after, headErr)
		}
		events, traceErr := os.ReadFile(trace)
		if traceErr != nil {
			t.Fatal(traceErr)
		}
		if !strings.Contains(string(events), "built-in: git clone") {
			t.Fatal("trace did not observe guidance retrieval")
		}
		for _, forbidden := range []string{"built-in: git commit", "built-in: git push"} {
			if strings.Contains(string(events), forbidden) {
				t.Fatalf("update ran forbidden Git operation %q", forbidden)
			}
		}
		t.Setenv("GIT_TRACE", "")
	}
}
