package integration

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/23min/aiwf/internal/cli/cliutil/testutil"
)

// Compare independent consumer repositories without normalizing artifact bytes.
// The snapshot excludes only health metadata, as documented by the Claude
// baseline. Its frozen expectations separately guard against a shared defect
// that produces the same wrong output everywhere.
func TestClaudeArtifacts_IndependentRootsAndRepeatedRefreshes(t *testing.T) {
	t.Parallel()
	testutil.SkipIfShortOrUnsupported(t)
	bin := testutil.BuildBinary(t, t.TempDir(), "-ldflags=-X github.com/23min/aiwf/internal/version.Stamp=v0.36.0")
	for _, tc := range []struct {
		name, config, wantImport string
		flags                    []string
	}{
		{name: "default", wantImport: ".claude/aiwf-guidance.md"},
		{
			name:       "configured",
			config:     "guidance:\n  wire_claudemd: false\nagents:\n  builder:\n    model: sonnet\n    effort: high\nhooks:\n  worktree-rituals-check.sh:\n    enabled: true\n",
			wantImport: ".claude/personal-guidance.md",
			flags:      []string{"--statusline", "--wire-settings"},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			const prefix = "User prefix: λ.\n\n<!-- aiwf:guidance:START - DO NOT EDIT, regenerated by aiwf update -->\n@"
			const suffix = "\n<!-- aiwf:guidance:END -->\n\nUser suffix.\n"
			foreign := map[string]struct {
				content string
				mode    os.FileMode
			}{
				".claude/skills/aiwf-personal/SKILL.md": {"Personal skill.\n", 0o644},
				".claude/skills/aiwf-personal/run.sh":   {"#!/bin/sh\nexit 0\n", 0o755},
				".claude/agents/personal.md":            {"Personal agent.\n", 0o644},
				".claude/templates/personal.md":         {"Personal template.\n", 0o644},
				".claude/personal-guidance.md":          {"Personal guidance.\n", 0o644},
				"notes.txt":                             {"Unrelated user notes.\n", 0o644},
			}
			var reference string
			for _, instance := range []string{"first", "second"} {
				root, home := filepath.Join(t.TempDir(), instance), t.TempDir()
				if err := os.Mkdir(root, 0o755); err != nil {
					t.Fatal(err)
				}
				git := func(args ...string) {
					t.Helper()
					claudeBaselineCommand(t, root, home, bin, "git", args...)
				}
				run := func(checkout string, args ...string) {
					t.Helper()
					claudeBaselineCommand(t, checkout, home, bin, bin, args...)
				}
				git("init", "-q", "-b", "main")
				git("config", "user.name", "aiwf-test")
				git("config", "user.email", "test@example.com")
				claudeBaselineWrite(t, home, ".claude/settings.json", "{\"permissions\":{\"allow\":[\"Read\"]}}\n")
				claudeBaselineWrite(t, root, ".claude/settings.json", "{\"permissions\":{\"allow\":[\"Read\"]}}\n")
				claudeBaselineWrite(t, root, "CLAUDE.md", prefix+".claude/personal-guidance.md"+suffix)
				claudeBaselineWrite(t, root, ".gitignore", "user-cache/\n")
				for path, fixture := range foreign {
					claudeBaselineWrite(t, root, path, fixture.content)
					if err := os.Chmod(filepath.Join(root, path), fixture.mode); err != nil {
						t.Fatal(err)
					}
				}
				if tc.config != "" {
					claudeBaselineWrite(t, root, "aiwf.yaml", tc.config)
				}
				initArgs := append([]string{"init", "--no-prompt"}, tc.flags...)
				run(root, initArgs...)
				if reference == "" {
					reference = claudeBaselineSnapshot(t, root, home, filepath.Join(root, ".git", "hooks"))
				}
				check := func(checkout, stage string) {
					t.Helper()
					got := claudeBaselineSnapshot(t, checkout, home, filepath.Join(root, ".git", "hooks"))
					if diff := cmp.Diff(reference, got); diff != "" {
						t.Errorf("%s %s artifacts differ (-first init +got):\n%s", instance, stage, diff)
					}
					if got := string(readFile(t, filepath.Join(checkout, "CLAUDE.md"))); got != prefix+tc.wantImport+suffix {
						t.Errorf("%s %s changed instruction text or guidance consent: %q", instance, stage, got)
					}
					for path, fixture := range foreign {
						absolute := filepath.Join(checkout, path)
						if got := string(readFile(t, absolute)); got != fixture.content {
							t.Errorf("%s %s changed user file %s: %q", instance, stage, path, got)
						}
						info, err := os.Stat(absolute)
						if err != nil {
							t.Fatal(err)
						}
						if info.Mode().Perm() != fixture.mode {
							t.Errorf("%s %s changed user file %s mode: %o", instance, stage, path, info.Mode().Perm())
						}
					}
				}
				check(root, "init")
				for round := range 2 {
					run(root, initArgs...)
					check(root, fmt.Sprintf("repeat init %d", round))
					// update exercises the shared RefreshArtifacts pipeline.
					run(root, "update")
					check(root, fmt.Sprintf("update %d", round))
				}
				git("add", "-A")
				git("add", "-f", ".claude/skills/aiwf-personal", ".claude/agents/personal.md", ".claude/templates/personal.md", ".claude/settings.json")
				git("commit", "-q", "-m", "chore: seed consumer configuration")
				worktree := filepath.Join(t.TempDir(), "checkout")
				run(root, "worktree", "add", "feature/equivalence", worktree)
				check(worktree, "worktree add")
				for round := range 2 {
					run(worktree, "update")
					check(worktree, fmt.Sprintf("worktree update %d", round))
				}
			}
		})
	}
}
