# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.4.2
_src_path: gh:23min/devcontainer-kit
aiwf: false
apt_packages: []
data_dir: false
dood: false
extra_extensions:
- github.vscode-github-actions
- shd101wyy.markdown-preview-enhanced
languages:
- node
- go
ports: {}
project_slug: aiwf
readonly_data: []
siblings: []
writable_siblings: []
