package policies

import (
	"path/filepath"
	"testing"
)

func TestPolicyDevcontainerWorkspaceMount(t *testing.T) {
	t.Parallel()
	runPolicy(t, PolicyDevcontainerWorkspaceMount)
}

// TestPolicyDevcontainerWorkspaceMount_Fixtures drives each way the policy
// can fire, plus a kit-shaped file that must pass: its // comment lines are
// part of what the reader has to accept.
func TestPolicyDevcontainerWorkspaceMount_Fixtures(t *testing.T) {
	t.Parallel()
	const repoMount = `"workspaceMount": "source=${localWorkspaceFolder},target=/workspaces/aiwf,type=bind"`
	cases := []struct {
		name   string
		files  map[string]string
		firing bool
	}{
		{name: "kit-shaped-passes", firing: false, files: map[string]string{
			devcontainerConfigPath: "// generated by devcontainer-kit\n{\n  // only this repo\n  " + repoMount + ",\n  \"mounts\": [\"source=/tmp/.aiwf-gh,target=/home/vscode/.config/gh,type=bind\"]\n}\n",
		}},
		{name: "missing", firing: true, files: map[string]string{}},
		{name: "not-json", firing: true, files: map[string]string{devcontainerConfigPath: "{ not json"}},
		{name: "no-workspace-mount", firing: true, files: map[string]string{devcontainerConfigPath: "{}"}},
		{name: "parent-workspace-mount", firing: true, files: map[string]string{
			devcontainerConfigPath: `{"workspaceMount": "source=${localWorkspaceFolder}/..,target=/workspaces/aiwf,type=bind"}`,
		}},
		{name: "wrong-target", firing: true, files: map[string]string{
			devcontainerConfigPath: `{"workspaceMount": "source=${localWorkspaceFolder},target=/workspaces,type=bind"}`,
		}},
		{name: "parent-in-mounts", firing: true, files: map[string]string{
			devcontainerConfigPath: "{" + repoMount + `, "mounts": ["source=${localWorkspaceFolder}/../other,target=/workspaces/other,type=bind"]}`,
		}},
		{name: "parent-in-mounts-short-spelling", firing: true, files: map[string]string{
			devcontainerConfigPath: "{" + repoMount + `, "mounts": ["src=${localWorkspaceFolder}/..,dst=/workspaces/all,type=bind"]}`,
		}},
		{name: "parent-in-run-args", firing: true, files: map[string]string{
			devcontainerConfigPath: "{" + repoMount + `, "runArgs": ["-v", "${localWorkspaceFolder}/..:/workspaces/all"]}`,
		}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			root := t.TempDir()
			for rel, content := range tc.files {
				mustWrite(t, filepath.Join(root, rel), content)
			}
			vs, err := PolicyDevcontainerWorkspaceMount(root)
			if err != nil {
				t.Fatalf("policy returned error: %v", err)
			}
			if got := len(vs) > 0; got != tc.firing {
				t.Errorf("fired = %v, want %v; violations: %v", got, tc.firing, vs)
			}
		})
	}
}
