package policies

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// PolicyM0132DevcontainerLock asserts that .devcontainer/devcontainer-lock.json
// pins resolved SHAs for every feature declared in devcontainer.json,
// matching FlowTime's reproducibility precedent.
//
// The lockfile is generated by `devcontainer build` (or
// `devcontainer outdated --apply`); it isn't authored by hand. This
// policy fires on shape problems once the file exists: missing
// features, missing version/resolved/integrity fields, or a resolved
// value that lacks an @sha256: pin (a versioned tag isn't a pin).
//
// Pins M-0132/AC-2. The companion test (m0132_devcontainer_lock_test.go)
// t.Skips while the lockfile is absent — the pre-first-build state —
// so this policy doesn't fail CI before the operator regenerates it.
func PolicyM0132DevcontainerLock(root string) ([]Violation, error) {
	const relLock = ".devcontainer/devcontainer-lock.json"
	const relJSON = ".devcontainer/devcontainer.json"
	absLock := filepath.Join(root, relLock)

	rawLock, err := os.ReadFile(absLock)
	if err != nil {
		return []Violation{{
			Policy: "m0132-devcontainer-lock",
			File:   relLock,
			Detail: fmt.Sprintf("missing or unreadable: %v (regenerate via `devcontainer outdated --apply` or by running the first `devcontainer build`)", err),
		}}, nil
	}

	var lock struct {
		Features map[string]struct {
			Version   string `json:"version"`
			Resolved  string `json:"resolved"`
			Integrity string `json:"integrity"`
		} `json:"features"`
	}
	if uerr := json.Unmarshal(rawLock, &lock); uerr != nil {
		return []Violation{{
			Policy: "m0132-devcontainer-lock",
			File:   relLock,
			Detail: fmt.Sprintf("not valid JSON: %v", uerr),
		}}, nil
	}

	// Cross-reference declared features in devcontainer.json.
	absJSON := filepath.Join(root, relJSON)
	rawJSON, err := os.ReadFile(absJSON)
	if err != nil {
		return []Violation{{
			Policy: "m0132-devcontainer-lock",
			File:   relLock,
			Detail: fmt.Sprintf("can't read %s for cross-reference: %v", relJSON, err),
		}}, nil
	}
	var cfg struct {
		Features map[string]any `json:"features"`
	}
	if uerr := json.Unmarshal(rawJSON, &cfg); uerr != nil {
		return []Violation{{
			Policy: "m0132-devcontainer-lock",
			File:   relLock,
			Detail: fmt.Sprintf("can't parse %s for cross-reference: %v", relJSON, uerr),
		}}, nil
	}

	var vs []Violation
	report := func(detail string) {
		vs = append(vs, Violation{
			Policy: "m0132-devcontainer-lock",
			File:   relLock,
			Detail: detail,
		})
	}

	// Every feature in devcontainer.json must be pinned in the lock.
	var missing []string
	for fid := range cfg.Features {
		if _, ok := lock.Features[fid]; !ok {
			missing = append(missing, fid)
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		report(fmt.Sprintf("features declared in devcontainer.json but missing from lockfile: %s", strings.Join(missing, ", ")))
	}

	// Each lockfile entry must carry non-empty version, an @sha256:
	// pinned resolved value, and a non-empty integrity field.
	keys := make([]string, 0, len(lock.Features))
	for k := range lock.Features {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, fid := range keys {
		e := lock.Features[fid]
		if e.Version == "" {
			report(fmt.Sprintf("feature %s: missing version", fid))
		}
		if e.Resolved == "" {
			report(fmt.Sprintf("feature %s: missing resolved", fid))
		} else if !strings.Contains(e.Resolved, "@sha256:") {
			report(fmt.Sprintf("feature %s: resolved %q lacks @sha256: prefix (not actually pinned)", fid, e.Resolved))
		}
		if e.Integrity == "" {
			report(fmt.Sprintf("feature %s: missing integrity", fid))
		}
	}

	return vs, nil
}
