package policies

import (
	"os"
	"path/filepath"
	"testing"
)

func TestPolicy_M0132DevcontainerLock(t *testing.T) {
	t.Parallel()
	// Skip while the lockfile is absent — that's the expected
	// pre-first-build state. The lockfile is generated by
	// `devcontainer build` (or `devcontainer outdated --apply`); once
	// it lands, **remove this skip** in the same commit and AC-2 is
	// ready to promote to met.
	root := repoRoot(t)
	if _, err := os.Stat(filepath.Join(root, ".devcontainer", "devcontainer-lock.json")); os.IsNotExist(err) {
		t.Skip("M-0132/AC-2: devcontainer-lock.json not yet generated; remove this skip when the operator commits the regenerated lockfile.")
	}
	runPolicy(t, PolicyM0132DevcontainerLock)
}
