package spec

import (
	"fmt"
	"html"
	"strconv"
	"strings"
)

// RenderReference renders the declared workflow model in declaration order.
// The result depends only on spec data, so it can be compared with a committed copy.
func RenderReference() []byte {
	return renderReference(Applicabilities(), Rules(), GlobalRules())
}

func renderReference(applicability []Applicability, rules, globals []Rule) []byte {
	var out strings.Builder
	out.WriteString(`# Workflow legality reference

Generated from the workflow specification. Do not edit this file by hand.
From the repository root, regenerate with:

` + "```sh\ngo run ./cmd/workflow-reference\n```\n" + `
This reference lists declared requests, their conditions and their outcomes.
Coordinate coverage means at least one row per applicable origin and verb;
it does not mean every possible target, argument or invocation is listed.
A missing request is not permission. Legal rows remain subject to their
conditions and the global restrictions below. All predicates in a row must hold.

The target is the requested target, not a claim that a refused request reaches it.
Legal means a mutation; NoOp means success without mutation; Illegal means refusal.
Rejection layer, strict blocking and error code describe the declared refusal.
A blank error code means no code is declared. Blank phase states mean unset;
blank global kind or verb fields mean the restriction is not limited by that field.
Empty predicate cells add no row-specific condition.

This is not a complete command reference or an executable workflow guide.
Branch choreography, anti-rules, undeclared argument constraints and the reasoning
behind decisions are outside this view. See the [workflow guide](../workflows.md)
for narrative usage and the [design decisions](../design/design-decisions.md)
for the project's commitments.

## Applicability

| Kind | Verb | Applies | Exclusion reason |
|---|---|---|---|
`)
	for _, a := range applicability {
		referenceRow(&out, string(a.Kind), a.Verb, strconv.FormatBool(a.Applies), a.Reason)
	}
	out.WriteString("\n## Declared transitions\n\n| Kind | From | Verb | Requested target | Outcome | Preconditions (AND) | Rejection layer | Strict blocking | Error code |\n|---|---|---|---|---|---|---|---|---|\n")
	for i := range rules {
		r := &rules[i]
		referenceRow(&out, string(r.Kind), r.FromState, r.Verb, r.ToState, referenceOutcome(r.Outcome), referencePredicates(r.Preconditions), referenceLayer(r.RejectionLayer), strconv.FormatBool(r.BlockingStrict), r.ExpectedErrorCode)
	}
	out.WriteString("\n## Global restrictions\n\n| Kind | Verb | Preconditions (AND) | Outcome | Rejection layer | Strict blocking | Error code |\n|---|---|---|---|---|---|---|\n")
	for i := range globals {
		r := &globals[i]
		referenceRow(&out, string(r.Kind), r.Verb, referencePredicates(r.Preconditions), referenceOutcome(r.Outcome), referenceLayer(r.RejectionLayer), strconv.FormatBool(r.BlockingStrict), r.ExpectedErrorCode)
	}
	return []byte(out.String())
}

func referenceRow(out *strings.Builder, cells ...string) {
	out.WriteString("|")
	for _, cell := range cells {
		out.WriteString(" " + referenceCell(cell) + " |")
	}
	out.WriteString("\n")
}

func referenceCell(value string) string {
	return strings.NewReplacer("\\", "\\\\", "|", "\\|", "`", "\\`", "*", "\\*", "_", "\\_", "[", "\\[", "]", "\\]", "\r\n", "<br>", "\r", "<br>", "\n", "<br>").Replace(html.EscapeString(value))
}

func referencePredicates(predicates []Predicate) string {
	var parts []string
	for _, p := range predicates {
		value := p.Value
		if value == "" && p.Op != "exists" && p.Op != "non-empty" {
			value = `""`
		}
		parts = append(parts, strings.TrimSpace(p.Subject+" "+p.Op+" "+value))
	}
	return strings.Join(parts, " AND ")
}

func referenceOutcome(outcome Outcome) string {
	switch outcome {
	case OutcomeUnspecified:
		return "Unspecified"
	case OutcomeLegal:
		return "Legal"
	case OutcomeIllegal:
		return "Illegal"
	case OutcomeNoOp:
		return "NoOp"
	default:
		return fmt.Sprintf("Unknown (%d)", outcome)
	}
}

func referenceLayer(layer RejectionLayer) string {
	switch layer {
	case RejectionLayerNone:
		return "none"
	case RejectionLayerVerbTime:
		return "verb-time"
	case RejectionLayerCheckTime:
		return "check-time"
	default:
		return fmt.Sprintf("unknown (%d)", layer)
	}
}
