package projectguidance

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/23min/aiwf/internal/testsupport"
)

func TestCheckCompatibility_InspectsInstalledChecker(t *testing.T) {
	for _, kind := range []string{"success", "refusal", "cannot execute", "cancelled"} {
		t.Run(kind, func(t *testing.T) {
			bin := testsupport.IsolateGuidanceEnvironment(t)
			checker := filepath.Join(bin, "dotfiles-guidance-check")
			body := "#!/bin/sh\nprintf 'checked both hosts\\n'\nexit 0\n"
			if kind == "refusal" {
				body = "#!/bin/sh\nprintf 'reconcile custom override\\n' >&2\nexit 1\n"
			}
			if kind == "cannot execute" {
				body = "#!/missing/interpreter\n"
			}
			if err := testsupport.WriteExecutable(checker, []byte(body)); err != nil {
				t.Fatal(err)
			}
			ctx, cancel := context.WithCancel(t.Context())
			defer cancel()
			if kind == "cancelled" {
				cancel()
			}
			err := CheckCompatibility(ctx)
			if kind == "success" {
				if err != nil {
					t.Fatal(err)
				}
				return
			}
			if err == nil {
				t.Fatal("failed checker accepted")
			}
			if kind == "refusal" && !strings.Contains(err.Error(), "reconcile custom override") {
				t.Fatalf("checker diagnostic lost: %v", err)
			}
		})
	}
}

func TestCheckCompatibility_MissingCheckerDetectsLegacyDelivery(t *testing.T) {
	for _, kind := range []string{"absent", "unrelated personal", "claude", "codex", "override", "empty override", "home launcher", "path launcher", "unreadable", "broken link", "directory", "linked instructions", "linked personal", "custom Codex profile", "override precedence", "default profiles", "missing home", "unsearchable directory", "unsearchable launcher directory"} {
		t.Run(kind, func(t *testing.T) {
			bin := testsupport.IsolateGuidanceEnvironment(t)
			home := os.Getenv("HOME")
			switch kind {
			case "unrelated personal":
				write(t, home, ".codex/AGENTS.md", "Personal preferences only.\n")
			case "claude":
				write(t, home, ".claude/CLAUDE.md", "# generated by ai-dotfiles\n")
			case "codex", "empty override":
				write(t, home, ".codex/AGENTS.md", "@~/.agents/guidance/200-go.md\n")
				if kind == "empty override" {
					write(t, home, ".codex/AGENTS.override.md", "")
				}
			case "override":
				write(t, home, ".codex/AGENTS.override.md", "# ai-dotfiles\n")
			case "home launcher":
				write(t, home, ".local/bin/dotfiles-sync", "legacy launcher\n")
			case "path launcher":
				if err := testsupport.WriteExecutable(filepath.Join(bin, "dotfiles-sync"), []byte("#!/bin/sh\nexit 0\n")); err != nil {
					t.Fatal(err)
				}
			case "unreadable":
				if os.Geteuid() == 0 {
					t.Skip("requires non-root")
				}
				write(t, home, ".claude/CLAUDE.md", "private\n")
				if err := os.Chmod(filepath.Join(home, ".claude", "CLAUDE.md"), 0); err != nil {
					t.Fatal(err)
				}
			case "default profiles":
				t.Setenv("CODEX_HOME", "")
				t.Setenv("CLAUDE_CONFIG_DIR", "")
				write(t, home, ".claude/CLAUDE.md", "# ai-dotfiles\n")
			case "custom Codex profile":
				custom := filepath.Join(home, "custom-codex")
				t.Setenv("CODEX_HOME", custom)
				write(t, custom, "AGENTS.md", "# ai-dotfiles\n")
			case "linked personal":
				write(t, home, ".codex/personal.md", "Personal rules only.\n")
				if err := os.Symlink("personal.md", filepath.Join(home, ".codex", "AGENTS.md")); err != nil {
					t.Fatal(err)
				}
			case "missing home":
				t.Setenv("HOME", "")
			case "directory":
				if err := os.MkdirAll(filepath.Join(home, ".claude", "CLAUDE.md"), 0o755); err != nil {
					t.Fatal(err)
				}
			case "linked instructions", "override precedence":
				write(t, home, ".codex/AGENTS.md", "# ai-dotfiles\n")
				if kind == "override precedence" {
					write(t, home, ".codex/AGENTS.override.md", "Personal override.\n")
				} else {
					if err := os.Symlink("AGENTS.md", filepath.Join(home, ".codex", "AGENTS.override.md")); err != nil {
						t.Fatal(err)
					}
				}
			case "unsearchable directory", "unsearchable launcher directory":
				if os.Geteuid() == 0 {
					t.Skip("requires non-root")
				}
				parent := filepath.Join(home, ".claude")
				if kind == "unsearchable launcher directory" {
					parent = filepath.Join(home, ".local")
				}
				if err := os.Mkdir(parent, 0o600); err != nil {
					t.Fatal(err)
				}
				t.Cleanup(func() { _ = os.Chmod(parent, 0o755) })
			case "broken link":
				if err := os.MkdirAll(filepath.Join(home, ".codex"), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.Symlink("missing", filepath.Join(home, ".codex", "AGENTS.override.md")); err != nil {
					t.Fatal(err)
				}
			}
			err := CheckCompatibility(t.Context())
			allowed := kind == "absent" || kind == "unrelated personal" || kind == "override precedence" || kind == "linked personal"
			if allowed && err != nil {
				t.Fatal(err)
			}
			if !allowed && (err == nil || !strings.Contains(err.Error(), "ai-dotfiles")) {
				t.Fatalf("legacy setup without checker accepted: %v", err)
			}
		})
	}
}
