package projectguidance

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

const legacyFixture = "<!-- ai-dotfiles:stack:START (generated by dotfiles-sync; do not edit) -->\n@~/.agents/guidance/200-go.md\n<!-- ai-dotfiles:stack:END -->"

const localLegacyFixture = "<!-- ai-dotfiles:stack:START (generated by dotfiles-sync; do not edit) -->\nRead .ai-dotfiles/engineering.md for this repository's engineering guidance.\n<!-- ai-dotfiles:stack:END -->"

func TestInstall_ReplacesLegacyDeliveryWithProjectRouting(t *testing.T) {
	t.Parallel()
	for _, tt := range []struct {
		name  string
		block string
		empty bool
	}{
		{"global imports", legacyFixture, false},
		{"global imports empty selection", legacyFixture, true},
		{"local route", localLegacyFixture, false},
		{"local route empty selection", localLegacyFixture, true},
	} {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			snapshot, opts := installationFixture(t)
			if tt.empty {
				opts.Selected = []string{}
			}
			root := t.TempDir()
			for _, host := range opts.HostFiles {
				write(t, root, host, "# Handwritten rules\n\n"+tt.block+"\n\nKeep this paragraph.\n")
			}
			if _, err := Install(t.Context(), root, snapshot, opts); err != nil {
				t.Fatal(err)
			}
			files := readTree(t, root)
			for _, host := range opts.HostFiles {
				if strings.Contains(files[host], "@~/.agents/guidance/") || strings.Contains(files[host], "ai-dotfiles:stack:") || strings.Contains(files[host], ".ai-dotfiles/engineering.md") {
					t.Fatalf("%s still loads legacy guidance", host)
				}
				if !strings.HasPrefix(files[host], "# Handwritten rules\n\n") || !strings.Contains(files[host], "\n\nKeep this paragraph.\n") || !strings.Contains(files[host], ".guidance/index.md") {
					t.Fatalf("lost handwritten content or replacement route: %s", files[host])
				}
			}
			if _, err := Install(t.Context(), root, snapshot, opts); err != nil {
				t.Fatal(err)
			}
			if diff := cmp.Diff(files, readTree(t, root)); diff != "" {
				t.Fatalf("handover does not converge: %s", diff)
			}
		})
	}
}

func TestInstall_RefusesAmbiguousLegacyHandoverBeforeWrites(t *testing.T) {
	t.Parallel()
	for _, kind := range []string{"malformed", "foreign block content", "personal import", "nested path", "backslash", "non-markdown", "whitespace", "unmanaged import", "unmanaged local route", "altered local route", "unselected host", "unselected local host"} {
		t.Run(kind, func(t *testing.T) {
			t.Parallel()
			snapshot, opts := installationFixture(t)
			root := t.TempDir()
			content := legacyFixture
			switch kind {
			case "malformed":
				content = strings.ReplaceAll(content, "<!-- ai-dotfiles:stack:END -->", "")
			case "foreign block content":
				content = strings.ReplaceAll(content, "@~/.agents/guidance/200-go.md", "My handwritten rule.")
			case "personal import":
				content = strings.ReplaceAll(content, "200-go.md", "000-general.md")
			case "nested path":
				content = strings.ReplaceAll(content, "200-go.md", "../private.md")
			case "backslash":
				content = strings.ReplaceAll(content, "200-go.md", `private\file.md`)
			case "non-markdown":
				content = strings.ReplaceAll(content, "200-go.md", "file.txt")
			case "whitespace":
				content = strings.ReplaceAll(content, "200-go.md", "two words.md")
			case "unmanaged import":
				content = "@~/.agents/guidance/200-go.md\n"
			case "unmanaged local route":
				content = "Read .ai-dotfiles/engineering.md for this repository's engineering guidance.\n"
			case "altered local route":
				content = strings.ReplaceAll(localLegacyFixture, "engineering.md", "custom.md")
			case "unselected local host":
				content = localLegacyFixture
				opts.HostFiles = []string{"AGENTS.md"}
			case "unselected host":
				opts.HostFiles = []string{"AGENTS.md"}
			}
			write(t, root, "CLAUDE.md", content)
			before := readTree(t, root)
			if _, err := Install(t.Context(), root, snapshot, opts); !errors.Is(err, ErrInstallConflict) {
				t.Fatalf("unsafe handover accepted: %v", err)
			}
			if diff := cmp.Diff(before, readTree(t, root)); diff != "" {
				t.Fatalf("refused handover changed files: %s", diff)
			}
		})
	}
}

func TestInstall_RecoversInterruptedLegacyHandoverWithChangedSelection(t *testing.T) {
	t.Parallel()
	snapshot, opts := installationFixture(t)
	root := t.TempDir()
	for _, host := range opts.HostFiles {
		write(t, root, host, "# Keep personal rules\n"+legacyFixture+"\n")
	}
	desired, err := renderInstallation(snapshot, opts)
	if err != nil {
		t.Fatal(err)
	}
	writes, _, err := planInstallation(t.Context(), root, desired, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	pending, err := stageInstallation(t.Context(), root, writes, nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := writeInstallRecord(root, pendingFile, pending); err != nil {
		t.Fatal(err)
	}
	// Model a process stopping after publishing one host route, before the index.
	for _, operation := range writes {
		if err := os.Rename(filepath.Join(root, operation.receipt.Temp), filepath.Join(root, operation.path)); err != nil {
			t.Fatal(err)
		}
		if hostFile(operation.path) {
			break
		}
	}
	partial := readTree(t, root)
	if _, exists := partial[indexFile]; exists {
		t.Fatal("interrupted handover prematurely published ownership")
	}
	if strings.Contains(partial["AGENTS.md"], legacyImport) || !strings.Contains(partial["CLAUDE.md"], legacyImport) {
		t.Fatal("fixture did not interrupt between host replacements")
	}
	opts.Selected = []string{}
	if _, err := Install(t.Context(), root, snapshot, opts); err != nil {
		t.Fatal(err)
	}
	files := readTree(t, root)
	if !strings.Contains(files[indexFile], snapshot.Commit) {
		t.Fatal("recovered index missing revision")
	}
	for name, content := range files {
		if strings.Contains(name, ".aiwf-tmp-") || name == pendingFile || strings.HasPrefix(name, ".guidance/packs/") {
			t.Fatalf("obsolete interrupted output remains: %s", name)
		}
		if hostFile(name) && (strings.Contains(content, legacyImport) || !strings.Contains(content, "# Keep personal rules")) {
			t.Fatalf("handover lost personal rules or retained legacy imports: %s", name)
		}
	}
}

func TestInstall_RemovesReintroducedLegacyBlockWithoutChangingRoute(t *testing.T) {
	t.Parallel()
	snapshot, opts := installationFixture(t)
	root := t.TempDir()
	if _, err := Install(t.Context(), root, snapshot, opts); err != nil {
		t.Fatal(err)
	}
	before := readTree(t, root)
	write(t, root, "CLAUDE.md", before["CLAUDE.md"]+legacyFixture+"\n")
	changed, err := Install(t.Context(), root, snapshot, opts)
	if err != nil || !changed {
		t.Fatalf("legacy cleanup skipped: changed=%v, err=%v", changed, err)
	}
	after := readTree(t, root)
	if strings.Contains(after["CLAUDE.md"], legacyImport) {
		t.Fatal("legacy imports remain")
	}
	if after[indexFile] != before[indexFile] || after[ownedFile] != before[ownedFile] {
		t.Fatal("cleanup changed installed policy or ownership")
	}
}

func TestInstall_RemovesBlankLegacyBlock(t *testing.T) {
	t.Parallel()
	snapshot, opts := installationFixture(t)
	root := t.TempDir()
	write(t, root, "CLAUDE.md", legacyStart+"\n  \n"+legacyEnd+"\n")
	if _, err := Install(t.Context(), root, snapshot, opts); err != nil {
		t.Fatal(err)
	}
	if strings.Contains(readTree(t, root)["CLAUDE.md"], legacyPrefix) {
		t.Fatal("blank legacy block remains")
	}
}
