package projectguidance

import (
	"fmt"
	"path"
	"strings"

	"github.com/23min/aiwf/internal/pathutil"
)

const (
	legacyStart      = "<!-- ai-dotfiles:stack:START (generated by dotfiles-sync; do not edit) -->"
	legacyEnd        = "<!-- ai-dotfiles:stack:END -->"
	legacyPrefix     = "<!-- ai-dotfiles:stack:"
	legacyImport     = "@~/.agents/guidance/"
	legacyLocalRoute = "Read .ai-dotfiles/engineering.md for this repository's engineering guidance."
)

// replacementInput removes only recognized generated legacy imports or local routing.
// All other legacy references require the owner to reconcile their instructions.
func replacementInput(name string, current []byte, selected bool) ([]byte, error) {
	content := string(current)
	start, end, err := pathutil.ManagedBlockSpan(content, legacyStart, legacyEnd, legacyPrefix)
	if err != nil {
		return nil, fmt.Errorf("%w: %s has malformed legacy guidance markers; reconcile its ai-dotfiles block before retrying: %w", ErrInstallConflict, name, err)
	}
	if start >= 0 {
		if !selected {
			return nil, fmt.Errorf("%w: %s retains legacy imports without selected replacement routing; enable its host wiring or reconcile the imports before retrying", ErrInstallConflict, name)
		}
		block := content[start:end]
		lines := strings.Split(block, "\n")
		for _, line := range lines[1 : len(lines)-1] {
			line = strings.TrimSpace(line)
			if line == "" || line == legacyLocalRoute {
				continue
			}
			module, ok := strings.CutPrefix(line, legacyImport)
			if !ok || module == "000-general.md" || path.Base(module) != module || !strings.HasSuffix(module, ".md") || strings.ContainsAny(module, "\\ \t\r") {
				return nil, fmt.Errorf("%w: %s legacy block contains unrecognized content; preserve and reconcile it before retrying", ErrInstallConflict, name)
			}
		}
		content = content[:start] + content[end:]
	}
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), legacyImport) || strings.Contains(line, ".ai-dotfiles/engineering.md") {
			return nil, fmt.Errorf("%w: %s contains handwritten legacy guidance references; reconcile them before retrying", ErrInstallConflict, name)
		}
	}
	return []byte(content), nil
}
