package projectguidance

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/23min/aiwf/internal/pathutil"
)

const (
	ownedFile   = ".guidance/.aiwf-owned"
	pendingFile = ".guidance/.aiwf-pending"
	indexFile   = ".guidance/index.md"
	routePrefix = "<!-- aiwf:engineering-guidance:"
	routeStart  = "<!-- aiwf:engineering-guidance:START - DO NOT EDIT, regenerated by aiwf update -->"
	routeEnd    = "<!-- aiwf:engineering-guidance:END -->"
)

// ErrInstallConflict identifies content that cannot safely be replaced.
var ErrInstallConflict = errors.New("project guidance installation conflict")

// InstallOptions selects project policy and host routing. Unselected host routes
// remain installed; handwritten project.md is never generated or owned.
type InstallOptions struct {
	Source    string
	Selected  []string
	HostFiles []string
}

type receipt struct {
	Before     string `json:"before"`
	After      string `json:"after"`
	Temp       string `json:"temp,omitempty"`
	TempDigest string `json:"temp_digest,omitempty"`
}

func (r receipt) recognizes(value string) bool {
	return value == r.Before || value == r.After
}

type installWrite struct {
	path    string
	content []byte
	mode    fs.FileMode
	receipt receipt
}

// RouteMarkers returns the start and end markers of the managed routing block
// and the prefix every marker of that block family carries, in the shape
// pathutil.ManagedBlockSpan takes.
func RouteMarkers() (start, end, prefix string) { return routeStart, routeEnd, routePrefix }

func digest(content []byte) string { return fmt.Sprintf("%x", sha256.Sum256(content)) }

func hostFile(name string) bool { return name == "AGENTS.md" || name == "CLAUDE.md" }

func validOwnedPath(name string) bool {
	return hostFile(name) || name == indexFile || (strings.HasPrefix(name, ".guidance/packs/") && strings.HasSuffix(name, ".md"))
}

func validDigest(value string) bool {
	raw, err := hex.DecodeString(value)
	return err == nil && len(raw) == sha256.Size && value == strings.ToLower(value)
}

func readInstallFile(ctx context.Context, root, name string) ([]byte, fs.FileMode, error) {
	info, err := pathutil.InspectArtifactPath(ctx, root, filepath.FromSlash(name))
	if err != nil {
		return nil, 0, err
	}
	if info == nil {
		return nil, 0o644, nil
	}
	if !info.Mode().IsRegular() {
		return nil, 0, fmt.Errorf("%w: %s is not a regular file", ErrInstallConflict, name)
	}
	content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
	if err != nil {
		return nil, 0, fmt.Errorf("reading %s: %w", name, err)
	}
	return content, info.Mode().Perm(), nil
}

func ownedBytes(name string, content []byte) ([]byte, error) {
	if !hostFile(name) {
		return content, nil
	}
	start, end, err := pathutil.ManagedBlockSpan(string(content), routeStart, routeEnd, routePrefix)
	if err != nil {
		return nil, fmt.Errorf("%w: %s has malformed project guidance markers: %w", ErrInstallConflict, name, err)
	}
	if start < 0 {
		return nil, nil
	}
	return content[start:end], nil
}

func readRecord[T any](ctx context.Context, root, name string) (map[string]T, error) {
	data, _, err := readInstallFile(ctx, root, name)
	if err != nil {
		return nil, err
	}
	record := make(map[string]T)
	if data == nil {
		return nil, nil
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&record); err != nil {
		return nil, fmt.Errorf("%w: reading %s: %w", ErrInstallConflict, name, err)
	}
	// A second JSON value or trailing non-whitespace is a corrupt record.
	if record == nil || len(bytes.TrimSpace(data[decoder.InputOffset():])) != 0 {
		return nil, fmt.Errorf("%w: malformed %s", ErrInstallConflict, name)
	}
	for path := range record {
		if !validOwnedPath(path) {
			return nil, fmt.Errorf("%w: %s contains an unowned path %q", ErrInstallConflict, name, path)
		}
		if _, err := pathutil.InspectArtifactPath(ctx, root, filepath.FromSlash(path)); err != nil {
			return nil, err
		}
	}
	return record, nil
}

func readInstallRecords(ctx context.Context, root string) (ownedRecord map[string]string, pendingRecord map[string]receipt, err error) {
	owned, err := readRecord[string](ctx, root, ownedFile)
	if err != nil {
		return nil, nil, err
	}
	for name, value := range owned {
		if !validDigest(value) {
			return nil, nil, fmt.Errorf("%w: invalid ownership digest for %s", ErrInstallConflict, name)
		}
	}
	pending, err := readRecord[receipt](ctx, root, pendingFile)
	if err != nil {
		return nil, nil, err
	}
	for name, entry := range pending {
		if (entry.Before != "" && !validDigest(entry.Before)) || (entry.After != "" && !validDigest(entry.After)) || (entry.Before == "" && entry.After == "") {
			return nil, nil, fmt.Errorf("%w: invalid recovery digest for %s", ErrInstallConflict, name)
		}
		if entry.Temp != "" {
			if filepath.ToSlash(filepath.Dir(entry.Temp)) != filepath.ToSlash(filepath.Dir(name)) || !strings.HasPrefix(filepath.Base(entry.Temp), filepath.Base(name)+".aiwf-tmp-") || !validDigest(entry.TempDigest) {
				return nil, nil, fmt.Errorf("%w: invalid recovery temporary path for %s", ErrInstallConflict, name)
			}
			content, _, err := readInstallFile(ctx, root, entry.Temp)
			if err != nil {
				return nil, nil, err
			}
			if content != nil && digest(content) != entry.TempDigest {
				return nil, nil, fmt.Errorf("%w: recovery temporary file %s was edited", ErrInstallConflict, entry.Temp)
			}
		}
	}
	return owned, pending, nil
}

// Install preflights the full selection, stages replacements, then publishes the
// index last. A pending receipt recognizes old and new bytes after interruption;
// the next invocation finishes using the current selection and source revision.
func Install(ctx context.Context, root string, snapshot *Snapshot, opts InstallOptions) (bool, error) {
	desired, err := renderInstallation(snapshot, opts)
	if err != nil {
		return false, err
	}
	owned, pending, err := readInstallRecords(ctx, root)
	if err != nil {
		return false, err
	}
	writes, nextOwned, err := planInstallation(ctx, root, desired, owned, pending)
	if err != nil {
		return false, err
	}
	if len(writes) == 0 && pending == nil {
		return false, nil
	}
	if err := applyInstallation(ctx, root, writes, nextOwned, pending); err != nil {
		return false, fmt.Errorf("guidance installation incomplete; rerun aiwf update to finish: %w", err)
	}
	return true, nil
}

func planInstallation(ctx context.Context, root string, desired map[string][]byte, owned map[string]string, pending map[string]receipt) ([]installWrite, map[string]string, error) {
	names := map[string]bool{"CLAUDE.md": true, "AGENTS.md": true}
	for name := range desired {
		names[name] = true
	}
	for name := range owned {
		names[name] = true
	}
	for name := range pending {
		names[name] = true
	}
	ordered := make([]string, 0, len(names))
	for name := range names {
		ordered = append(ordered, name)
	}
	slices.Sort(ordered)
	// Publishing the ownership index is the final content write.
	ordered = append(slices.DeleteFunc(ordered, func(name string) bool { return name == indexFile }), indexFile)
	nextOwned := make(map[string]string)
	var writes []installWrite
	for _, name := range ordered {
		current, mode, err := readInstallFile(ctx, root, name)
		if err != nil {
			return nil, nil, err
		}
		input := current
		if hostFile(name) {
			_, selected := desired[name]
			input, err = replacementInput(name, current, selected)
			if err != nil {
				return nil, nil, err
			}
		}
		target, selected := desired[name]
		if hostFile(name) && !selected {
			// Retain the recorded digest so reselecting the host still detects edits.
			if prior, known := owned[name]; known {
				nextOwned[name] = prior
			} else if interrupted, recovering := pending[name]; recovering && interrupted.After != "" {
				nextOwned[name] = interrupted.After
			}
			if interrupted, recovering := pending[name]; recovering {
				block, blockErr := ownedBytes(name, current)
				if blockErr == nil && block != nil && interrupted.recognizes(digest(block)) {
					nextOwned[name] = digest(block)
				}
			}
			continue
		}
		currentOwned, err := ownedBytes(name, current)
		if err != nil {
			return nil, nil, err
		}
		before := ""
		if currentOwned != nil {
			before = digest(currentOwned)
		}
		prior, known := owned[name]
		interrupted, recovering := pending[name]
		if before != "" && (!known || before != prior) && (!recovering || !interrupted.recognizes(before)) {
			return nil, nil, fmt.Errorf("%w: %s is foreign or locally edited; preserve your changes in project.md or reconcile the generated file before retrying", ErrInstallConflict, name)
		}
		if selected && hostFile(name) {
			replacement, err := pathutil.SpliceManagedBlock(string(input), string(target), routeStart, routeEnd, routePrefix)
			if err != nil { //coverage:ignore ownedBytes already validated these same immutable current bytes and markers
				return nil, nil, err
			}
			target = []byte(replacement)
		}
		after := ""
		if selected {
			targetOwned, err := ownedBytes(name, target)
			if err != nil {
				return nil, nil, err
			}
			after = digest(targetOwned)
			nextOwned[name] = after
		}
		if before == after && (!hostFile(name) || bytes.Equal(current, target)) {
			continue
		}
		writes = append(writes, installWrite{path: name, content: target, mode: mode, receipt: receipt{Before: before, After: after}})
	}
	return writes, nextOwned, nil
}

func applyInstallation(ctx context.Context, root string, writes []installWrite, owned map[string]string, prior map[string]receipt) error {
	defer func() {
		for _, operation := range writes {
			if operation.receipt.Temp != "" {
				_ = os.Remove(filepath.Join(root, filepath.FromSlash(operation.receipt.Temp)))
			}
		}
	}()
	pending, err := stageInstallation(ctx, root, writes, prior)
	if err != nil {
		return err
	}
	return publishInstallation(ctx, root, writes, owned, pending)
}

func stageInstallation(ctx context.Context, root string, writes []installWrite, prior map[string]receipt) (map[string]receipt, error) {
	pending := make(map[string]receipt)
	// Retain evidence for already-published files until final ownership is durable.
	for name, entry := range prior {
		entry.Temp, entry.TempDigest = "", ""
		pending[name] = entry
	}
	for i := range writes {
		operation := &writes[i]
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if operation.content != nil {
			destination := filepath.Join(root, filepath.FromSlash(operation.path))
			if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
				return nil, fmt.Errorf("creating parent for %s: %w", operation.path, err)
			}
			staged, err := pathutil.StageAtomicWriteFile(destination, operation.content, operation.mode)
			if err != nil {
				return nil, err
			}
			operation.receipt.Temp = filepath.ToSlash(filepath.Join(filepath.Dir(operation.path), filepath.Base(staged)))
			operation.receipt.TempDigest = digest(operation.content)
		}
		pending[operation.path] = operation.receipt
	}
	for _, entry := range prior {
		if entry.Temp != "" {
			if err := os.Remove(filepath.Join(root, filepath.FromSlash(entry.Temp))); err != nil && !errors.Is(err, fs.ErrNotExist) {
				return nil, err
			}
		}
	}
	return pending, nil
}

func publishInstallation(ctx context.Context, root string, writes []installWrite, owned map[string]string, pending map[string]receipt) error {
	if err := writeInstallRecord(root, pendingFile, pending); err != nil {
		return err
	}
	for _, operation := range writes {
		if err := ctx.Err(); err != nil {
			return err
		}
		destination := filepath.Join(root, filepath.FromSlash(operation.path))
		if operation.content == nil {
			if err := os.Remove(destination); err != nil && !errors.Is(err, fs.ErrNotExist) {
				return fmt.Errorf("retiring %s: %w", operation.path, err)
			}
		} else if err := os.Rename(filepath.Join(root, filepath.FromSlash(operation.receipt.Temp)), destination); err != nil {
			return fmt.Errorf("installing %s: %w", operation.path, err)
		}
	}
	if err := writeInstallRecord(root, ownedFile, owned); err != nil {
		return err
	}
	if err := os.Remove(filepath.Join(root, pendingFile)); err != nil { //coverage:ignore requires concurrent permission revocation or device failure after writing in this same parent
		return fmt.Errorf("removing completed recovery record: %w", err)
	}
	return nil
}

func writeInstallRecord(root, name string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return fmt.Errorf("encoding %s: %w", name, err)
	}
	return pathutil.AtomicWriteFile(filepath.Join(root, filepath.FromSlash(name)), append(data, '\n'), 0o644)
}
