package projectguidance

import (
	"strings"
	"testing"
)

func TestInstall_RetainedHostPreservesPublishedRecoveryDigest(t *testing.T) {
	t.Parallel()
	s, o := installationFixture(t)
	r := t.TempDir()
	if _, e := Install(t.Context(), r, s, o); e != nil {
		t.Fatal(e)
	}
	owned, _, e := readInstallRecords(t.Context(), r)
	if e != nil {
		t.Fatal(e)
	}
	current, _, e := readInstallFile(t.Context(), r, "AGENTS.md")
	if e != nil {
		t.Fatal(e)
	}
	block, e := ownedBytes("AGENTS.md", current)
	if e != nil {
		t.Fatal(e)
	}
	old := strings.Replace(string(block), "Handwritten project overrides", "Project overrides", 1)
	owned["AGENTS.md"] = digest([]byte(old))
	if e = writeInstallRecord(r, ownedFile, owned); e != nil {
		t.Fatal(e)
	}
	pending := map[string]receipt{"AGENTS.md": {Before: digest([]byte(old)), After: digest(block)}}
	if e = writeInstallRecord(r, pendingFile, pending); e != nil {
		t.Fatal(e)
	}
	o.HostFiles = []string{"CLAUDE.md"}
	if _, e = Install(t.Context(), r, s, o); e != nil {
		t.Fatal(e)
	}
	report, e := Inspect(t.Context(), r)
	if e != nil {
		t.Fatal(e)
	}
	if report.Pending || len(report.Issues) != 0 {
		t.Fatalf("unexpected recovery damage: %+v", report)
	}
	o.HostFiles = append(o.HostFiles, "AGENTS.md")
	if _, e = Install(t.Context(), r, s, o); e != nil {
		t.Fatalf("generated route accepted by pending receipt must remain accepted after recovery: %v", e)
	}
}

func TestInstall_DisabledMalformedRouteIsRetainedAndReported(t *testing.T) {
	t.Parallel()
	s, o := installationFixture(t)
	r := t.TempDir()
	if _, e := Install(t.Context(), r, s, o); e != nil {
		t.Fatal(e)
	}
	write(t, r, "AGENTS.md", routeStart)
	o.HostFiles = []string{"CLAUDE.md"}
	s.Documents["packs/go/cobra/guide.md"] = []byte("updated")
	if _, e := Install(t.Context(), r, s, o); e != nil {
		t.Fatal(e)
	}
	report, e := Inspect(t.Context(), r)
	if e != nil {
		t.Fatal(e)
	}
	if len(report.Issues) != 1 || report.Issues[0].Path != "AGENTS.md" {
		t.Fatalf("%+v", report)
	}
}

func TestInspect_PublishedPendingBytesAreNotUserEdits(t *testing.T) {
	t.Parallel()
	s, o := installationFixture(t)
	r := t.TempDir()
	if _, e := Install(t.Context(), r, s, o); e != nil {
		t.Fatal(e)
	}
	const file = ".guidance/packs/go/cobra/guide.md"
	old, _, e := readInstallFile(t.Context(), r, file)
	if e != nil {
		t.Fatal(e)
	}
	const fresh = "# New generated guidance\n"
	write(t, r, file, fresh)
	if e = writeInstallRecord(r, pendingFile, map[string]receipt{file: {Before: digest(old), After: digest([]byte(fresh))}}); e != nil {
		t.Fatal(e)
	}
	report, e := Inspect(t.Context(), r)
	if e != nil {
		t.Fatal(e)
	}
	for _, issue := range report.Issues {
		if strings.Contains(issue.Detail, "locally modified") {
			t.Fatalf("published generated bytes called local edits: %+v", report)
		}
	}
}
