package stresstest

import (
	"encoding/json"
	"errors"
	"fmt"
	"math/rand/v2"
	"os/exec"
	"strconv"
	"strings"

	"github.com/23min/aiwf/internal/check"
	"github.com/23min/aiwf/internal/entity"
)

// verb_sequence.go — M-0241/AC-1: VerbSequenceScenario drives a
// random walk of `aiwf promote` calls, via the real compiled
// binary, against one real entity of every kind in one disposable
// git repo. It extends internal/entity/transition_property_test.go's
// pattern (which only exercises entity.ValidateTransition in-process)
// out to the real binary: after every step it confirms the FSM's
// legality verdict is honored and that `aiwf check` never regresses,
// per M-0241/AC-1.

// verbSequenceExpectedWarnings is the baseline of finding codes any
// check in this scenario's disposable repo is expected to carry,
// independent of anything the scenario itself probes:
//
//   - provenance-untrailered-scope-undefined: the repo never
//     configures an upstream remote, so the provenance audit range
//     is permanently undefined.
//   - epic-active-no-drafted-milestones: the scenario's one epic
//     reaches "active" (and stays there) while never carrying a
//     draft-status milestone — the milestone entity this scenario
//     also creates gets walked away from "draft" independently, and
//     no second milestone is ever added to replace it.
//   - terminal-entity-not-archived / archive-sweep-pending: the
//     random walk drives entities to terminal statuses (done,
//     rejected, wontfix, ...) routinely, and this scenario never
//     runs `aiwf archive` — both are advisory-only sweep reminders,
//     not evidence of anything this scenario probes.
//
// Any OTHER finding — any error-severity finding, or a warning with
// a code not in this set — is a real violation this scenario reports.
var verbSequenceExpectedWarnings = map[string]bool{
	check.CodeProvenanceUntrailedScopeUndefined: true,
	check.CodeEpicActiveNoDraftedMilestones:     true,
	check.CodeTerminalEntityNotArchived:         true,
	check.CodeArchiveSweepPending:               true,
}

// verbEnvelope is the subset of the uniform `--format=json` envelope
// (CLAUDE.md "Output": {tool,version,status,findings,result,metadata})
// this scenario reads. Different verbs populate different subsets of
// Result/Metadata; decoding the same shape for every verb is simpler
// than one type per verb since the unused fields just stay zero.
type verbEnvelope struct {
	Status   string                `json:"status"`
	Error    *verbEnvelopeError    `json:"error"`
	Findings []verbEnvelopeFinding `json:"findings"`
	Result   struct {
		ID     string `json:"id"`
		Status string `json:"status"`
	} `json:"result"`
	Metadata struct {
		EntityID string `json:"entity_id"`
	} `json:"metadata"`
}

type verbEnvelopeError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type verbEnvelopeFinding struct {
	Code     string `json:"code"`
	Severity string `json:"severity"`
}

// VerbSequenceScenario implements Scenario. steps is the number of
// promote attempts run per entity kind.
type VerbSequenceScenario struct {
	aiwfBin    string
	rng        *rand.Rand
	steps      int
	violations []Violation
}

// NewVerbSequenceScenario builds a scenario that walks `steps`
// promote attempts per kind, seeded for reproducibility.
func NewVerbSequenceScenario(aiwfBin string, seed int64, steps int) *VerbSequenceScenario {
	return &VerbSequenceScenario{
		aiwfBin: aiwfBin,
		rng:     rand.New(rand.NewPCG(uint64(seed), uint64(seed))), //nolint:gosec // seeded PCG for reproducible replay, not a security context
		steps:   steps,
	}
}

// Setup git-inits dir and sets a deterministic commit identity.
func (s *VerbSequenceScenario) Setup(dir string) error {
	return gitInitAndConfig(dir)
}

// Run creates one entity of every kind (in entity.AllKinds() order,
// so the milestone's --epic parent already exists) and walks each
// through s.steps random promote attempts.
func (s *VerbSequenceScenario) Run(dir string) error {
	var epicID string
	for _, kind := range entity.AllKinds() {
		args := []string{
			"add", string(kind),
			"--title", fmt.Sprintf("stress %s", kind),
			"--body", "generated by the verb-sequence stress scenario",
		}
		if kind == entity.KindMilestone {
			args = append(args, "--epic", epicID, "--tdd", "none")
		}

		addEnv, err := runAiwfJSON(s.aiwfBin, dir, args...)
		if err != nil { //coverage:ignore defensive: covered by TestVerbSequenceScenario_RealBinary_RunErrorsWhenBinaryMissing at the source (runAiwfJSON's own launch-failure branch), not by re-triggering it at every call site
			return fmt.Errorf("creating a %s entity: %w", kind, err)
		}
		if addEnv.Status != "ok" {
			return fmt.Errorf("creating a %s entity: aiwf did not report ok (status=%s, error=%+v, findings=%+v)",
				kind, addEnv.Status, addEnv.Error, addEnv.Findings)
		}
		id := addEnv.Metadata.EntityID
		if kind == entity.KindEpic {
			epicID = id
		}

		showEnv, err := runAiwfJSON(s.aiwfBin, dir, "show", id)
		if err != nil { //coverage:ignore defensive: same launch-failure class as the `add` call above; `show` on a just-created valid id has no realistic failure mode of its own
			return fmt.Errorf("reading initial status of %s: %w", id, err)
		}
		current := showEnv.Result.Status
		if current == "" { //coverage:ignore defensive: `show`'s JSON contract always populates result.status for a valid entity id
			return fmt.Errorf("could not determine initial status of %s", id)
		}

		if err := s.walk(dir, kind, id, current); err != nil { //coverage:ignore defensive: walk's own internal error branches are the same launch-failure class, pinned at their source
			return err
		}
	}
	return nil
}

// Verify returns every violation walk collected across every kind.
func (s *VerbSequenceScenario) Verify(_ string) []Violation {
	return s.violations
}

// walk runs s.steps promote attempts against id, picking a target
// status uniformly at random from the kind's full closed status set
// (so both FSM-legal and FSM-illegal targets are exercised) and
// classifying the outcome via classifyVerbSequenceStep. After every
// attempt it also re-runs `aiwf check` and classifies its findings.
func (s *VerbSequenceScenario) walk(dir string, kind entity.Kind, id, current string) error {
	targets := entity.AllowedStatuses(kind)
	for i := 0; i < s.steps; i++ {
		target := targets[s.rng.IntN(len(targets))]

		before, err := gitHeadCommitCount(dir)
		if err != nil { //coverage:ignore defensive: git rev-list on a repo this scenario itself just created and is still driving has no realistic failure mode
			return fmt.Errorf("counting commits before %s %s -> %s: %w", id, current, target, err)
		}
		env, err := runAiwfJSON(s.aiwfBin, dir, "promote", id, target)
		if err != nil { //coverage:ignore defensive: same launch-failure class pinned at its source by TestVerbSequenceScenario_RealBinary_RunErrorsWhenBinaryMissing
			return fmt.Errorf("running promote %s %s: %w", id, target, err)
		}
		after, err := gitHeadCommitCount(dir)
		if err != nil { //coverage:ignore defensive: see the "before" call above
			return fmt.Errorf("counting commits after %s %s -> %s: %w", id, current, target, err)
		}

		next, violations := classifyVerbSequenceStep(kind, current, target, before, after, env)
		s.violations = append(s.violations, violations...)
		current = next

		checkEnv, err := runAiwfJSON(s.aiwfBin, dir, "check")
		if err != nil { //coverage:ignore defensive: same launch-failure class pinned at its source by TestVerbSequenceScenario_RealBinary_RunErrorsWhenBinaryMissing
			return fmt.Errorf("running aiwf check after %s %s -> %s: %w", id, current, target, err)
		}
		s.violations = append(s.violations, classifyCheckFindings(checkEnv.Findings)...)
	}
	return nil
}

// runAiwfJSON runs bin with args plus --format=json in dir and
// decodes the resulting envelope. A non-zero exit is expected
// traffic (an FSM refusal, a business-rule refusal) and is not
// itself an error — only a process that fails to even run, or
// output that isn't valid JSON, returns an error. Package-level
// (not a method) so every scenario in this package can point it at
// whichever directory it's driving — e.g. one of several sibling
// worktrees, not just the scenario's own single dir.
func runAiwfJSON(bin, dir string, args ...string) (verbEnvelope, error) {
	cmd := exec.Command(bin, append(args, "--format=json")...) //nolint:gosec // bin is a path this package's own BuildBinary just produced, not attacker-controlled input
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		var exitErr *exec.ExitError
		if !errors.As(err, &exitErr) {
			return verbEnvelope{}, fmt.Errorf("running aiwf %v: %w", args, err)
		}
	}
	return parseVerbEnvelope(args, out)
}

// parseVerbEnvelope decodes one --format=json invocation's stdout.
// Split out of runAiwfJSON so the malformed-output path is directly
// unit-testable without a real subprocess.
func parseVerbEnvelope(args []string, out []byte) (verbEnvelope, error) {
	var env verbEnvelope
	if err := json.Unmarshal(out, &env); err != nil {
		return verbEnvelope{}, fmt.Errorf("parsing aiwf %v JSON output: %w\n%s", args, err, out)
	}
	return env, nil
}

// gitHeadCommitCount returns the number of commits reachable from
// HEAD in dir.
func gitHeadCommitCount(dir string) (int, error) {
	cmd := exec.Command("git", "rev-list", "--count", "HEAD")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil { //coverage:ignore defensive: git rev-list on a repo this scenario itself just created has no realistic failure mode
		return 0, fmt.Errorf("counting commits in %s: %w", dir, err)
	}
	return parseCommitCount(out)
}

// parseCommitCount parses `git rev-list --count`'s stdout. Split out
// of gitHeadCommitCount so the malformed-output path is directly
// unit-testable without a real git subprocess.
func parseCommitCount(out []byte) (int, error) {
	n, err := strconv.Atoi(strings.TrimSpace(string(out)))
	if err != nil {
		return 0, fmt.Errorf("parsing commit count %q: %w", out, err)
	}
	return n, nil
}

// classifyVerbSequenceStep judges one promote attempt's outcome
// against the FSM's own legality verdict (entity.ValidateTransition),
// returning the resulting current status and any violations found.
//
// An FSM-illegal target must always be refused specifically with
// CodeFSMTransitionIllegal, and must never land a commit — that
// direction is unconditional. An FSM-legal target may still be
// refused for an orthogonal business rule (e.g. a gap's
// addressed-status resolver requirement) that sits outside the FSM
// proper; that refusal is legitimate as long as it isn't also
// tagged fsm-transition-illegal and it lands no commit. Whenever
// the verb reports success, exactly one commit must land.
func classifyVerbSequenceStep(kind entity.Kind, current, target string, before, after int, env verbEnvelope) (next string, violations []Violation) {
	legal := entity.ValidateTransition(kind, current, target) == nil
	refusedAsIllegal := env.Status == "error" && env.Error != nil && env.Error.Code == entity.CodeFSMTransitionIllegal.ID

	if env.Status == "ok" {
		if !legal {
			violations = append(violations, Violation{Message: fmt.Sprintf(
				"%s: FSM-illegal %s -> %s was accepted (status ok) instead of refused", kind, current, target)})
		}
		if after != before+1 {
			violations = append(violations, Violation{Message: fmt.Sprintf(
				"%s: promote %s -> %s reported success but landed %d commits, want exactly 1", kind, current, target, after-before)})
		}
		if legal {
			return target, violations
		}
		return current, violations
	}

	// Refused. Legitimate for either reason (FSM-illegal, or an
	// orthogonal business rule) as long as the refusal reason
	// matches the FSM's own verdict and no commit landed.
	if !legal && !refusedAsIllegal {
		violations = append(violations, Violation{Message: fmt.Sprintf(
			"%s: FSM-illegal %s -> %s was not refused as %s (status=%s, error=%+v)",
			kind, current, target, entity.CodeFSMTransitionIllegal.ID, env.Status, env.Error)})
	}
	if legal && refusedAsIllegal {
		violations = append(violations, Violation{Message: fmt.Sprintf(
			"%s: FSM-legal %s -> %s was refused as %s", kind, current, target, entity.CodeFSMTransitionIllegal.ID)})
	}
	if after != before {
		violations = append(violations, Violation{Message: fmt.Sprintf(
			"%s: refused promote %s -> %s still landed a commit (%d -> %d)", kind, current, target, before, after)})
	}
	return current, violations
}

// classifyCheckFindings reports a violation for every finding that
// isn't part of verbSequenceExpectedWarnings — any error-severity
// finding always violates, regardless of code.
func classifyCheckFindings(findings []verbEnvelopeFinding) []Violation {
	var violations []Violation
	for _, f := range findings {
		if f.Severity == "error" || !verbSequenceExpectedWarnings[f.Code] {
			violations = append(violations, Violation{Message: fmt.Sprintf(
				"unexpected aiwf check finding: %s (%s)", f.Code, f.Severity)})
		}
	}
	return violations
}
