package skills

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/23min/aiwf/internal/pathutil"
)

// Ownership errors distinguish collisions, unsafe paths, and corrupt records.
var (
	ErrOwnershipConflict  = errors.New("artifact ownership conflict")
	ErrUnsafeArtifactPath = pathutil.ErrUnsafeArtifactPath
	ErrInvalidOwnership   = errors.New("invalid artifact ownership record")
)

// PendingManifestFile records expected new artifact bytes until the ownership
// manifest commits them. It is removed after a successful family refresh.
const (
	PendingManifestFile       = ".aiwf-pending"
	pendingHeader             = "aiwf-pending-v1"
	provenanceOwnershipMarker = "<!-- Generated by aiwf; regenerated on every `aiwf init` / `aiwf update`. Do not commit edits. -->"
)

type artifactFamily struct {
	dir        string
	skills     bool
	files      []Skill
	provenance []byte
}

type artifactReceipt struct {
	name   string
	digest string
}

type artifactPlan struct {
	family     artifactFamily
	prior      []string
	pending    []artifactReceipt
	recovered  bool
	hadPending bool
}

func validArtifactName(name string) bool {
	if name == "" || name[0] == '.' || name == ProvenanceReadme {
		return false
	}
	for _, ch := range name {
		switch {
		case ch >= 'a' && ch <= 'z', ch >= 'A' && ch <= 'Z', ch >= '0' && ch <= '9', ch == '-', ch == '_', ch == '.':
		default:
			return false
		}
	}
	return true
}

func checkedArtifactPath(ctx context.Context, root, relative string) (fs.FileInfo, error) {
	return pathutil.InspectArtifactPath(ctx, root, relative)
}

func readOwnershipRecord(ctx context.Context, root, relative string) (content []byte, exists bool, err error) {
	info, err := checkedArtifactPath(ctx, root, relative)
	if err != nil {
		return nil, false, err
	}
	if info == nil {
		return nil, false, nil
	}
	if !info.Mode().IsRegular() {
		return nil, false, fmt.Errorf("%w: %s must be a regular file; repair the record before retrying", ErrInvalidOwnership, relative)
	}
	raw, err := os.ReadFile(filepath.Join(root, relative))
	if err != nil {
		return nil, false, fmt.Errorf("reading ownership record %s: %w", relative, err)
	}
	return raw, true, nil
}

func parseOwnedNames(raw []byte) ([]string, error) {
	var names []string
	seen := map[string]bool{}
	for _, name := range strings.Split(string(raw), "\n") {
		if name == "" {
			continue
		}
		if !validArtifactName(name) || seen[name] {
			return nil, fmt.Errorf("%w: unsafe or duplicate name %q", ErrInvalidOwnership, name)
		}
		names = append(names, name)
		seen[name] = true
	}
	return names, nil
}

func parseArtifactReceipts(raw []byte) ([]artifactReceipt, error) {
	lines := strings.Split(string(raw), "\n")
	if lines[0] != pendingHeader {
		return nil, fmt.Errorf("%w: unrecognized pending format", ErrInvalidOwnership)
	}
	var receipts []artifactReceipt
	seen := map[string]bool{}
	for _, line := range lines[1:] {
		if line == "" {
			continue
		}
		digest, name, ok := strings.Cut(line, " ")
		decoded, err := hex.DecodeString(digest)
		if !ok || err != nil || len(decoded) != sha256.Size || !validArtifactName(name) || seen[name] {
			return nil, fmt.Errorf("%w: malformed or duplicate pending entry %q", ErrInvalidOwnership, line)
		}
		receipts = append(receipts, artifactReceipt{name: name, digest: hex.EncodeToString(decoded)})
		seen[name] = true
	}
	return receipts, nil
}

func artifactDigest(content []byte) string { return fmt.Sprintf("%x", sha256.Sum256(content)) }

func inspectFamilyArtifact(ctx context.Context, root string, family artifactFamily, name string) (entryInfo, contentInfo fs.FileInfo, err error) {
	relative := filepath.Join(family.dir, name)
	base, err := checkedArtifactPath(ctx, root, relative)
	if err != nil {
		return nil, nil, err
	}
	if base == nil {
		return nil, nil, nil
	}
	if family.skills {
		if !base.IsDir() {
			return nil, nil, ownershipCollision(relative)
		}
		file, readErr := checkedArtifactPath(ctx, root, filepath.Join(relative, "SKILL.md"))
		if readErr != nil {
			return nil, nil, readErr
		}
		if file != nil && !file.Mode().IsRegular() {
			return nil, nil, ownershipCollision(filepath.Join(relative, "SKILL.md"))
		}
		return base, file, nil
	}
	if !base.Mode().IsRegular() {
		return nil, nil, ownershipCollision(relative)
	}
	return base, base, nil
}

func ownershipCollision(path string) error {
	return fmt.Errorf("%w: %s is not established as an aiwf-owned artifact; move the conflicting content or restore its ownership record before retrying", ErrOwnershipConflict, path)
}

func planArtifactFamily(ctx context.Context, root string, family artifactFamily) (artifactPlan, error) {
	plan := artifactPlan{family: family}
	info, err := checkedArtifactPath(ctx, root, family.dir)
	if err != nil {
		return plan, err
	}
	if info != nil && !info.IsDir() {
		return plan, fmt.Errorf("%w: %s is not a directory", ErrUnsafeArtifactPath, family.dir)
	}
	raw, _, err := readOwnershipRecord(ctx, root, filepath.Join(family.dir, ManifestFile))
	if err != nil {
		return plan, err
	}
	plan.prior, err = parseOwnedNames(raw)
	if err != nil {
		return plan, fmt.Errorf("reading %s/%s: %w; repair the record before retrying", family.dir, ManifestFile, err)
	}
	raw, plan.hadPending, err = readOwnershipRecord(ctx, root, filepath.Join(family.dir, PendingManifestFile))
	if err != nil {
		return plan, err
	}
	if plan.hadPending {
		plan.pending, err = parseArtifactReceipts(raw)
		if err != nil {
			return plan, fmt.Errorf("reading %s/%s: %w; repair the record before retrying", family.dir, PendingManifestFile, err)
		}
	}
	owned := map[string]bool{}
	for _, name := range plan.prior {
		owned[name] = true
	}
	pending := map[string]int{}
	for i, receipt := range plan.pending {
		pending[receipt.name] = i
		if owned[receipt.name] {
			continue
		}
		_, file, inspectErr := inspectFamilyArtifact(ctx, root, family, receipt.name)
		if inspectErr != nil {
			return plan, inspectErr
		}
		if file == nil {
			continue
		}
		path := filepath.Join(root, family.dir, receipt.name)
		if family.skills {
			path = filepath.Join(path, "SKILL.md")
		}
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return plan, fmt.Errorf("verifying pending artifact %s: %w", path, readErr)
		}
		if artifactDigest(content) != receipt.digest {
			return plan, ownershipCollision(path)
		}
		owned[receipt.name] = true
		plan.prior = append(plan.prior, receipt.name)
		plan.recovered = true
	}
	// Validate retired entries too: no deletion may traverse an unsafe path.
	for _, name := range plan.prior {
		if _, _, inspectErr := inspectFamilyArtifact(ctx, root, family, name); inspectErr != nil {
			return plan, inspectErr
		}
	}
	current := map[string]bool{}
	for _, file := range family.files {
		if !validArtifactName(file.Name) || current[file.Name] {
			return plan, fmt.Errorf("%w: unsafe or duplicate artifact name %q", ErrUnsafeArtifactPath, file.Name)
		}
		current[file.Name] = true
		base, _, inspectErr := inspectFamilyArtifact(ctx, root, family, file.Name)
		if inspectErr != nil {
			return plan, inspectErr
		}
		if owned[file.Name] {
			continue
		}
		index, hasReceipt := pending[file.Name]
		if base != nil && !hasReceipt {
			return plan, ownershipCollision(filepath.Join(family.dir, file.Name))
		}
		receipt := artifactReceipt{name: file.Name, digest: artifactDigest(file.Content)}
		if hasReceipt {
			plan.pending[index] = receipt
		} else {
			plan.pending = append(plan.pending, receipt)
		}
	}
	if family.provenance != nil {
		path := filepath.Join(family.dir, ProvenanceReadme)
		info, inspectErr := checkedArtifactPath(ctx, root, path)
		if inspectErr != nil {
			return plan, inspectErr
		}
		if info != nil {
			if !info.Mode().IsRegular() {
				return plan, ownershipCollision(path)
			}
			content, readErr := os.ReadFile(filepath.Join(root, path))
			if readErr != nil {
				return plan, fmt.Errorf("reading provenance %s: %w", path, readErr)
			}
			if !hasProvenanceOwnership(content) {
				return plan, ownershipCollision(path)
			}
		}
	}
	return plan, nil
}

func materializeArtifactFamilies(ctx context.Context, root string, families []artifactFamily) error {
	plans := make([]artifactPlan, 0, len(families))
	for i, family := range families {
		for _, other := range families[:i] {
			if family.dir == other.dir || strings.HasPrefix(family.dir, other.dir+string(filepath.Separator)) || strings.HasPrefix(other.dir, family.dir+string(filepath.Separator)) {
				return fmt.Errorf("%w: artifact roots %q and %q overlap", ErrUnsafeArtifactPath, family.dir, other.dir)
			}
		}
		plan, err := planArtifactFamily(ctx, root, family)
		if err != nil {
			return err
		}
		plans = append(plans, plan)
	}
	for i := range plans {
		if err := applyArtifactPlan(ctx, root, plans[i]); err != nil {
			return err
		}
	}
	return nil
}

func writeOwnershipNames(ctx context.Context, dir string, names []string) error {
	if err := ctx.Err(); err != nil {
		return fmt.Errorf("writing ownership manifest %s: %w", dir, err)
	}
	var text strings.Builder
	for _, name := range names {
		text.WriteString(name)
		text.WriteByte('\n')
	}
	if err := pathutil.AtomicWriteFile(filepath.Join(dir, ManifestFile), []byte(text.String()), 0o644); err != nil {
		return fmt.Errorf("writing ownership manifest %s: %w", dir, err)
	}
	return nil
}

func applyArtifactPlan(ctx context.Context, root string, plan artifactPlan) error {
	if err := ctx.Err(); err != nil {
		return fmt.Errorf("materializing %s: %w", plan.family.dir, err)
	}
	family := plan.family
	dir := filepath.Join(root, family.dir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", family.dir, err)
	}
	// Persist verified recovery before refreshing its bytes. A later interruption
	// can then rely on ownership even if this binary renders different content.
	if plan.recovered {
		if err := writeOwnershipNames(ctx, dir, plan.prior); err != nil {
			return err
		}
	}
	if len(plan.pending) > 0 {
		var receipt strings.Builder
		receipt.WriteString(pendingHeader + "\n")
		for _, entry := range plan.pending {
			receipt.WriteString(entry.digest + " " + entry.name + "\n")
		}
		if err := pathutil.AtomicWriteFile(filepath.Join(dir, PendingManifestFile), []byte(receipt.String()), 0o644); err != nil {
			return fmt.Errorf("writing recovery receipt %s: %w", dir, err)
		}
	}
	current := make(map[string]bool, len(family.files))
	names := make([]string, 0, len(family.files))
	for _, file := range family.files {
		current[file.Name] = true
		names = append(names, file.Name)
	}
	for _, name := range plan.prior {
		if current[name] {
			continue
		}
		if err := removeOwnedArtifact(ctx, dir, name, family.skills); err != nil {
			return err
		}
	}
	for _, file := range family.files {
		path := filepath.Join(dir, file.Name)
		if family.skills {
			if err := os.MkdirAll(path, 0o755); err != nil {
				return fmt.Errorf("creating skill %s: %w", path, err)
			}
			path = filepath.Join(path, "SKILL.md")
		}
		if err := pathutil.AtomicWriteFile(path, file.Content, 0o644); err != nil {
			return fmt.Errorf("writing artifact %s: %w", path, err)
		}
	}
	if family.provenance != nil {
		if err := pathutil.AtomicWriteFile(filepath.Join(dir, ProvenanceReadme), family.provenance, 0o644); err != nil {
			return fmt.Errorf("writing provenance %s: %w", dir, err)
		}
	}
	if err := writeOwnershipNames(ctx, dir, names); err != nil {
		return err
	}
	if plan.hadPending || len(plan.pending) > 0 {
		if err := os.Remove(filepath.Join(dir, PendingManifestFile)); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("removing recovery receipt %s: %w", dir, err)
		}
	}
	return nil
}

func removeOwnedArtifact(ctx context.Context, dir, name string, skill bool) error {
	if err := ctx.Err(); err != nil {
		return fmt.Errorf("retiring artifact %s: %w", name, err)
	}
	path := filepath.Join(dir, name)
	file := path
	if skill {
		file = filepath.Join(path, "SKILL.md")
	}
	if err := os.Remove(file); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("retiring artifact %s: %w", file, err)
	}
	if !skill {
		return nil
	}
	entries, err := os.ReadDir(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspecting retired skill %s: %w", path, err)
	}
	// Supplemental content is not owned by the generated SKILL.md record.
	if len(entries) > 0 {
		return nil
	}
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("removing empty retired skill %s: %w", path, err)
	}
	return nil
}

func hasProvenanceOwnership(content []byte) bool {
	for _, line := range strings.Split(string(content), "\n") {
		if line == provenanceOwnershipMarker {
			return true
		}
	}
	return false
}
