#!/usr/bin/env bash
# aiwf-statusline version: __AIWF_VERSION__ — managed by aiwf; regenerated by `aiwf update` (local edits are overwritten).
# Status line for Claude Code in the aiwf repo.
# Reads JSON from stdin (Claude Code's session context), prints one line.
#
# Layout: <ball> <model> <effort?> ▸ <tokens> · <epic HUD> · <repo> · <branch…>[<dirty>][<sync>] · <ci-glyph> ci
#
# All segments fail soft: anything that errors collapses to "?" or is dropped.
# Network + check-probe calls are cached in /tmp with a TTL so the hot
# (cache-hit) path stays fast; a cache miss pays one gh + one aiwf check --fast.

set -u

# Skip the opportunistic `.git/index.lock` write that `git status` (and
# other "read-only" callers) take to refresh the stat-cache on the way
# through. The render only reads, so the write is pure cost — and a
# SIGKILLed render dying mid-rename would orphan the lock, blocking the
# next real `git commit` in the same repo until someone cleans it up.
# Equivalent to prefixing every git call with `--no-optional-locks`,
# but cheaper: one export, every child inherits. Available since git 2.15.
export GIT_OPTIONAL_LOCKS=0

# Read everything from stdin once (Claude Code passes session JSON).
input="$(cat 2>/dev/null || true)"

jq_get() {
  # $1 = jq filter; prints empty string on any failure.
  printf '%s' "$input" | jq -r "$1 // empty" 2>/dev/null
}

# --- Model + context window -------------------------------------------------

model="$(jq_get '.model.display_name')"
[ -z "$model" ] && model="$(jq_get '.model.id')"
[ -z "$model" ] && model="?"

# Compress "Opus 4.7 (1M context)" → "Opus 4.7". The "(1M context)" suffix
# is implicit in the high ctx_max threshold + colored ball; redundant now
# that the token count sits inline next to the model name.
model_short="${model% (*}"

# Detect 1M-context variant from the display name.
case "$model" in
  *"1M"*|*"1m"*) ctx_max=1000000 ;;
  *)             ctx_max=200000  ;;
esac

# --- Token usage from transcript -------------------------------------------

transcript="$(jq_get '.transcript_path')"
tokens=0
if [ -n "$transcript" ] && [ -r "$transcript" ]; then
  # Walk transcript bottom-up; first assistant message with usage wins.
  # tail -r is BSD/macOS; tac is GNU. Brace-group so both branches
  # feed jq — `|` binds tighter than `||`, so without the group a
  # successful `tail -r` would route its raw output to the command
  # substitution and bypass the jq filter entirely.
  tokens="$({ tail -r "$transcript" 2>/dev/null || tac "$transcript" 2>/dev/null; } \
    | jq -r 'select(.message.usage != null)
             | .message.usage
             | (.input_tokens // 0)
             + (.cache_read_input_tokens // 0)
             + (.cache_creation_input_tokens // 0)' 2>/dev/null \
    | head -n 1)"
  [ -z "$tokens" ] && tokens=0
fi

# Format token count: 116k, 1.2M, 950 etc.
fmt_tokens() {
  local t="$1"
  if [ "$t" -ge 1000000 ]; then
    awk -v t="$t" 'BEGIN { printf "%.1fM", t/1000000 }'
  elif [ "$t" -ge 1000 ]; then
    awk -v t="$t" 'BEGIN { printf "%.0fk", t/1000 }'
  else
    printf '%s' "$t"
  fi
}
# Color thresholds — same scale for ball and token text.
# green <50%, yellow <80%, red >=80% (start a new session soon).
pct=$(( tokens * 100 / ctx_max ))
if   [ "$pct" -lt 50 ]; then color=$'\033[32m'   # green
elif [ "$pct" -lt 80 ]; then color=$'\033[33m'   # yellow
else                         color=$'\033[31m'   # red
fi
red=$'\033[31m'
blue=$'\033[34m'
yellow=$'\033[33m'
green=$'\033[32m'
gray=$'\033[90m'
bold=$'\033[1m'
reset=$'\033[0m'
ball="${color}●${reset}"
tokens_fmt="${color}$(fmt_tokens "$tokens")${reset}"

effort="$(jq_get '.effort.level')"

# entity_color maps an aiwf entity status to the four-color status palette:
#   blue   = proposed
#   yellow = in-flight / not-yet-terminal (draft/active/in_progress/open)
#   green  = terminal-success (done/addressed/accepted/met/retired)
#   red    = terminal-failure (cancelled/wontfix/rejected/deprecated/superseded)
# Unrecognized statuses return empty (id renders in the default terminal color).
entity_color() {
  case "$1" in
    proposed) printf '%s' "$blue" ;;
    draft|active|in_progress|open) printf '%s' "$yellow" ;;
    done|addressed|accepted|met|retired) printf '%s' "$green" ;;
    cancelled|wontfix|rejected|deprecated|superseded) printf '%s' "$red" ;;
  esac
}

# read_status pulls the `status:` value from an entity file's frontmatter.
# Unquoted values only (the aiwf writer emits unquoted statuses).
read_status() {
  awk '/^status:/{
    sub(/^status:[[:space:]]*/, "")
    sub(/[[:space:]]+$/, "")
    print
    exit
  }' "$1" 2>/dev/null
}

# --- Repo name --------------------------------------------------------------
#
# The MAIN repo's name, stable across linked worktrees. A worktree's
# --show-toplevel is the worktree dir (e.g. .../worktrees/G-0304), which would
# render the worktree's id as the repo name and duplicate the session-entity HUD
# (G-0304). --git-common-dir points every worktree at the one shared .git, so
# its parent is always the main repo root.

repo=""
common_dir="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)"
[ -n "$common_dir" ] && repo="$(basename "$(dirname "$common_dir")")"
# Fallbacks: older git without --path-format, then the session's cwd.
[ -z "$repo" ] && repo="$(git rev-parse --show-toplevel 2>/dev/null | xargs -I{} basename {} 2>/dev/null)"
[ -z "$repo" ] && repo="$(jq_get '.workspace.current_dir' | xargs -I{} basename {} 2>/dev/null)"
[ -z "$repo" ] && repo="?"

# --- Branch + dirty + sync --------------------------------------------------

branch_seg=""
cur_branch=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  if br="$(git symbolic-ref --short HEAD 2>/dev/null)"; then
    branch_seg="$br"
    cur_branch="$br"
  else
    sha="$(git rev-parse --short HEAD 2>/dev/null)"
    branch_seg="@${sha:-?}"
  fi

  # Truncate long branch names: keep first 30 chars, append …
  if [ "${#branch_seg}" -gt 30 ]; then
    branch_seg="${branch_seg:0:30}…"
  fi

  # Dirty marker: ✎ (pencil) for uncommitted changes, prefixed before branch.
  if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    branch_seg="✎ ${branch_seg}"
  fi

  # Sync state vs upstream.
  if up="$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)" && [ -n "$up" ]; then
    counts="$(git rev-list --left-right --count HEAD..."$up" 2>/dev/null)"
    # Default-IFS read splits on space or tab — survives editor / patch-tool
    # reflow that retabs the source. Empty $counts (no upstream output)
    # leaves both vars unset; the ${ahead:-0} / ${behind:-0} guards below
    # cover that case.
    read -r ahead behind <<<"$counts"
    sync=""
    [ "${ahead:-0}" -gt 0 ] 2>/dev/null && sync="${sync}↑${ahead}"
    [ "${behind:-0}" -gt 0 ] 2>/dev/null && sync="${sync}↓${behind}"
    branch_seg="${branch_seg}${sync}"
  fi
fi

# --- Session-entity HUD (G-0188, narrowed/extended by G-0304) ---------------
#
# Show ONLY the entity the current session is working in, with its status glyph
# (→ active, ○ proposed/draft/open, ✓ done/addressed, ✗ cancelled/…) and color:
#   - Ritual branch (epic/E-*, milestone/M-*): the current epic — the one the
#     branch belongs to — plus its milestone inline on a milestone branch.
#   - Patch branch (patch/G-NNNN-*): the gap the wf-patch is fixing.
#   - Anything else (main, gap-less patch/<slug>, …): nothing. The session isn't
#     in an entity, so the backlog belongs in `aiwf status`, not the statusline
#     (G-0304, superseding the earlier in-flight-list behavior).
#
# The ctx_* derivation below decides whether — and which — entity renders.

status_glyph() {
  case "$1" in
    active|in_progress) printf '→' ;;
    proposed|draft|open) printf '○' ;;
    done|addressed|accepted|met|retired) printf '✓' ;;
    cancelled|wontfix|rejected|superseded) printf '✗' ;;
    *) printf '?' ;;
  esac
}

# Derive the current-branch context (epic id, milestone id). On a milestone
# branch the epic id comes from the milestone file (git ls-files), so an
# as-yet-uncommitted milestone leaves ctx_epic_id empty and the HUD renders
# nothing — acceptable: the entity is not tracked yet.
ctx_epic_id=""
ctx_milestone_id=""
ctx_gap_id=""
case "$cur_branch" in
  milestone/M-*)
    ctx_milestone_id="$(printf '%s' "$cur_branch" | sed -E 's|^milestone/(M-[0-9]+).*|\1|')"
    m_file="$(git ls-files "work/epics/*/${ctx_milestone_id}-*.md" "work/epics/archive/*/${ctx_milestone_id}-*.md" 2>/dev/null | head -1)"
    if [ -n "$m_file" ]; then
      ctx_epic_id="$(printf '%s' "$m_file" | sed -E 's|^work/epics/(archive/)?(E-[0-9]+).*|\2|')"
    fi
    ;;
  epic/E-*)
    ctx_epic_id="$(printf '%s' "$cur_branch" | sed -E 's|^epic/(E-[0-9]+).*|\1|')"
    ;;
  patch/G-*)
    ctx_gap_id="$(printf '%s' "$cur_branch" | sed -E 's|^patch/(G-[0-9]+).*|\1|')"
    ;;
esac

ctx_hud=""
if [ -n "$ctx_epic_id" ]; then
  # Ritual epic/milestone branch: the current epic, with its milestone inline on
  # a milestone branch. Shown regardless of status (you are on its branch).
  e_file="$(git ls-files "work/epics/${ctx_epic_id}-*/epic.md" "work/epics/archive/${ctx_epic_id}-*/epic.md" 2>/dev/null | head -1)"
  e_status=""
  [ -n "$e_file" ] && e_status="$(read_status "$e_file")"
  e_clr="$(entity_color "$e_status")"
  e_glyph="$(status_glyph "$e_status")"
  ctx_hud="${bold}${e_clr}▸ ${e_glyph} ${ctx_epic_id}${reset}"
  if [ -n "$ctx_milestone_id" ]; then
    m_file="$(git ls-files "work/epics/*/${ctx_milestone_id}-*.md" "work/epics/archive/*/${ctx_milestone_id}-*.md" 2>/dev/null | head -1)"
    m_status=""
    [ -n "$m_file" ] && m_status="$(read_status "$m_file")"
    m_clr="$(entity_color "$m_status")"
    m_glyph="$(status_glyph "$m_status")"
    ctx_hud="${ctx_hud}${gray}/${reset}${m_clr}${m_glyph} ${ctx_milestone_id}${reset}"
  fi
elif [ -n "$ctx_gap_id" ]; then
  # Patch branch (patch/G-NNNN-*): the gap this wf-patch is fixing, with its
  # status glyph/color — the same session-entity treatment epics get (G-0304).
  g_file="$(git ls-files "work/gaps/${ctx_gap_id}-*.md" "work/gaps/archive/${ctx_gap_id}-*.md" 2>/dev/null | head -1)"
  g_status=""
  [ -n "$g_file" ] && g_status="$(read_status "$g_file")"
  g_clr="$(entity_color "$g_status")"
  g_glyph="$(status_glyph "$g_status")"
  ctx_hud="${bold}${g_clr}▸ ${g_glyph} ${ctx_gap_id}${reset}"
fi
# On a non-ritual / non-patch branch all three ctx ids are empty, so ctx_hud
# stays empty and no session-entity segment renders (G-0304).

# --- Other in-flight ritual worktrees count (+N⎇) --------------------------
#
# Counts other worktrees on ritual branches (epic/E-*, milestone/M-*,
# patch/[Gg]-*). The current session's worktree is excluded — the segment
# answers "is parallel work happening?" not "what's in flight overall".
# Omitted entirely when zero so single-session repos see no chrome.

other_wt_count=0
cur_wt="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -n "$cur_wt" ]; then
  while IFS= read -r line; do
    case "$line" in
      "worktree "*) wt_path="${line#worktree }" ;;
      "branch refs/heads/"*)
        wt_branch="${line#branch refs/heads/}"
        case "$wt_branch" in
          epic/E-*|milestone/M-*|patch/[Gg]-*)
            [ "$wt_path" != "$cur_wt" ] && other_wt_count=$((other_wt_count + 1))
            ;;
        esac
        ;;
    esac
  done < <(git worktree list --porcelain 2>/dev/null)
fi

# --- CI status (cached) -----------------------------------------------------

ci_state="?"
ci_prefix=""
if command -v gh >/dev/null 2>&1 && [ -n "$branch_seg" ]; then
  ci_branch="${cur_branch:-HEAD}"
  # --verify yields "" (not the literal "HEAD") on an unborn branch, so the
  # staleness guard's emptiness check below stays correct.
  head_sha="$(git rev-parse --verify HEAD 2>/dev/null)"
  # HEAD is folded into the cache key so a new commit (or a push that moves
  # HEAD) invalidates a prior verdict immediately, instead of the TTL serving
  # the pre-commit result for up to $ttl seconds. (G-0189)
  cache_key="$(printf '%s/%s/%s' "$(git rev-parse --show-toplevel 2>/dev/null)" "$ci_branch" "$head_sha" | shasum | awk '{print $1}')"
  # Cache dir is overridable (hermetic tests point it at a temp dir); /tmp
  # otherwise.
  cache_dir="${AIWF_STATUSLINE_CACHE_DIR:-/tmp}"
  cache_file="${cache_dir}/aiwf-statusline-ci-${cache_key}"
  ttl=45

  fetch_ci() {
    # $1 = branch, $2 = expected HEAD sha ("" → use the latest run's commit, the
    # main-fallback proxy). Aggregates ALL workflow runs for the target commit
    # to the worst state, so one failed workflow is never masked by a passing
    # sibling that happens to be the most-recent run (G-0303). Returns the stale
    # glyph (…) when no run exists for the expected HEAD — its verdict would be
    # for a different commit (G-0189). Any failure → ✗; else any still-running →
    # →; else any success → ✓ (tolerating benign skipped/neutral siblings from
    # path-filtered or if:-gated workflows); else ? (e.g. all skipped).
    local b="$1" expected_sha="$2" out
    out="$(gh run list --branch "$b" --limit 30 --json conclusion,status,headSha 2>/dev/null)" || return 1
    [ -z "$out" ] || [ "$out" = "[]" ] && return 1
    printf '%s' "$out" | jq -r --arg sha "$expected_sha" '
      (if $sha == "" then (.[0].headSha // "") else $sha end) as $target
      | map(select(.headSha == $target)) as $runs
      | if   ($runs | length) == 0 then "…"
        elif any($runs[]; .conclusion=="failure" or .conclusion=="cancelled" or .conclusion=="timed_out" or .conclusion=="action_required" or .conclusion=="startup_failure") then "✗"
        elif any($runs[]; .status=="in_progress" or .status=="queued" or .status=="requested" or .status=="waiting") then "→"
        elif any($runs[]; .conclusion=="success") then "✓"
        else "?"
        end' 2>/dev/null
  }

  use_cache=false
  if [ -r "$cache_file" ]; then
    age=$(( $(date +%s) - $(stat -c %Y "$cache_file" 2>/dev/null || stat -f %m "$cache_file" 2>/dev/null || echo 0) ))
    [ "$age" -lt "$ttl" ] && use_cache=true
  fi

  if $use_cache; then
    cached="$(cat "$cache_file" 2>/dev/null)"
    ci_prefix="${cached%%|*}"
    ci_state="${cached##*|}"
  else
    s="$(fetch_ci "$ci_branch" "$head_sha")"
    if [ -z "$s" ] || [ "$s" = "?" ]; then
      # Fall back to main when the current branch has no runs. No staleness
      # check here: main's HEAD is not the current checkout's HEAD, and the
      # m: prefix already signals this is a proxy, not your branch.
      if [ "$ci_branch" != "main" ]; then
        s="$(fetch_ci main "")"
        [ -n "$s" ] && [ "$s" != "?" ] && ci_prefix="m:"
      fi
    fi
    [ -z "$s" ] && s="?"
    ci_state="$s"
    tmp="${cache_file}.tmp.$$"
    printf '%s|%s' "$ci_prefix" "$ci_state" >"$tmp" 2>/dev/null && mv -f "$tmp" "$cache_file" 2>/dev/null
  fi
fi

# CI glyph precedes the label: ✓ ci / ✗ ci / → ci / … ci / ? ci.
# Color matches the glyph's meaning: green ✓, red ✗, yellow →, gray … (stale:
# the latest run is for a different commit than HEAD, so its verdict does not
# apply to what's checked out). Main-fallback prefix surfaces as ✓ m:ci.
ci_label="ci"
[ -n "$ci_prefix" ] && ci_label="${ci_prefix}${ci_label}"
case "$ci_state" in
  '✓') ci_fmt="${green}${ci_state} ${ci_label}${reset}" ;;
  '✗') ci_fmt="${red}${ci_state} ${ci_label}${reset}" ;;
  '→') ci_fmt="${yellow}${ci_state} ${ci_label}${reset}" ;;
  '…') ci_fmt="${gray}${ci_state} ${ci_label}${reset}" ;;
  *)   ci_fmt="${ci_state} ${ci_label}" ;;
esac

# --- Installation health stoplight (reads producer health files) -----------
#
# Reads .claude/health.*.json — one per producer (aiwf, ai-dotfiles, …) — unions
# their findings, and prefixes a four-state stoplight at the maximum severity:
#   ▲ (red)    — a finding is error severity
#   ▲ (yellow) — the max severity is warn
#   ● (green)  — a health file present with no warn/error (healthy)
#   ● (gray)   — an aiwf repo but no producer has written a file yet (unknown)
# It NEVER runs a check on the render path: producers write the files out of band
# (`aiwf doctor --write-health`, `dotfiles-doctor --write`); the statusline only
# reads and unions. Resolves to the MAIN checkout (git-common-dir parent) so one
# file serves every linked worktree. Severities are matched by substring; a
# corrupt file among valid ones contributes no match, and a set with no readable
# "findings" at all renders gray (unknown) rather than a false green.

health_prefix=""
health_common="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)"
if [ -n "$health_common" ]; then
  health_root="$(dirname "$health_common")"
  set -- "$health_root/.claude"/health.*.json
  if [ -e "$1" ]; then
    health_blob="$(cat "$health_root/.claude"/health.*.json 2>/dev/null)"
    if ! printf '%s' "$health_blob" | grep -q '"findings"'; then
      # files present but none parse (no "findings" key) — unknown, not a
      # false green (ADR-0026: "no health file present, or none parse").
      health_prefix="${gray}●${reset} "
    elif printf '%s' "$health_blob" | grep -q '"severity"[[:space:]]*:[[:space:]]*"error"'; then
      health_prefix="${red}▲${reset} "
    elif printf '%s' "$health_blob" | grep -q '"severity"[[:space:]]*:[[:space:]]*"warn"'; then
      health_prefix="${yellow}▲${reset} "
    else
      health_prefix="${green}●${reset} "
    fi
  elif [ -f "$health_root/aiwf.yaml" ]; then
    health_prefix="${gray}●${reset} "
  fi
fi

# --- Subscription-usage dots (G-0310) --------------------------------------
# rate_limits.{seven_day,five_hour}.used_percentage from the stdin JSON — the
# figures /usage shows (Pro/Max only, present after the first API response, each
# window independently optional). One colored dot + label per present window,
# same green/yellow/red scale as the context ball; an absent window renders
# nothing (like the health glyph degrades).
usage_color() {  # $1 = integer percent
  if   [ "$1" -lt 50 ]; then printf '%s' "$green"
  elif [ "$1" -lt 80 ]; then printf '%s' "$yellow"
  else                       printf '%s' "$red"
  fi
}
usage_seg=""
usage_dot() {  # $1 = raw used_percentage (float/int/empty), $2 = label
  case "$1" in
    ''|*[!0-9.]*) return ;;            # absent or non-numeric -> render nothing
  esac
  local _u; _u="${1%%.*}"; [ -z "$_u" ] && _u=0  # truncate float -> int for comparison
  usage_seg="${usage_seg} $(usage_color "$_u")●${reset} $2"
}
usage_dot "$(jq_get '.rate_limits.seven_day.used_percentage')" "7d"
usage_dot "$(jq_get '.rate_limits.five_hour.used_percentage')" "5h"

# --- Compose ----------------------------------------------------------------

head_seg="$ball $model_short"
[ -n "$effort" ] && head_seg="$head_seg ${gray}${effort}${reset}"
head_seg="$head_seg ▸ $tokens_fmt"
[ -n "$usage_seg" ] && head_seg="$head_seg$usage_seg"
parts=("$head_seg")
[ -n "$ctx_hud" ]       && parts+=("$ctx_hud")
parts+=("$repo")
[ -n "$branch_seg" ]    && parts+=("$branch_seg")
[ "$other_wt_count" -gt 0 ] && parts+=("+${other_wt_count}⎇")
parts+=("$ci_fmt")

# Join with " · ".
out=""
for p in "${parts[@]}"; do
  if [ -z "$out" ]; then out="$p"; else out="$out · $p"; fi
done
printf '%s%s' "$health_prefix" "$out"
